Repository sakura-editor/sakura, pull requests merged in 2018-10, with the labels that each got.

#452 ステータスバーのテキスト設定、既に同じ値が設定されている場合は再設定しないようにする
  sakura_core/apiwrap/CommonControl.h
  sakura_core/view/CCaret.cpp
  sakura_core/window/CMainStatusBar.cpp
  sakura_core/window/CMainStatusBar.h
Labels: speed up

#521 ヘッダのプロトタイプ宣言で明示的に変数名を指定する (CCodeMediator)
  sakura_core/charset/CCodeMediator.h
Labels: CI, refactoring

#522 ヘッダのプロトタイプ宣言で明示的に変数名を指定する (CESI)
  sakura_core/charset/CESI.h
Labels: CI, refactoring

#528 bregonig/ctags のライセンスが artifacts に含まれないバグを修正
  zipArtifacts.bat
Labels: CI, license

#529 LICENSE ファイルをインストーラと artifacts のzip ファイルに含める
  build-installer.bat
  installer/sakura-common.iss
  zipArtifacts.bat
Labels: CI, installer, license

#537 ヘッダのプロトタイプ宣言で明示的に変数名を指定する (CCodeBase の派生クラス)
  sakura_core/charset/CCodePage.h
  sakura_core/charset/CEuc.h
  sakura_core/charset/CJis.h
  sakura_core/charset/CLatin1.h
  sakura_core/charset/CShiftJis.h
  sakura_core/charset/CUtf7.h
  sakura_core/charset/CUtf8.h
Labels: refactoring

#534 英語windowsでメッセージがおかしい件に対処する
  sakura_core/CSelectLang.cpp
Labels: Internationalization, bug

#544 ループ変数と vecLine のサイズを size_t で定義する
  sakura_core/CProfile.cpp
Labels: refactoring

#545 windows95向けの独自定義サイズマクロをやめる
  sakura_core/apiwrap/StdApi.h
  sakura_core/dlg/CDlgOpenFile.cpp
  sakura_core/dlg/CDlgOpenFile.h
  sakura_core/prop/CPropCommon.cpp
  sakura_core/typeprop/CPropTypes.cpp
  sakura_core/uiparts/CMenuDrawer.cpp
Labels: refactoring

#546 ビルドシンボル定義の整理
  sakura/sakura.vcxproj
  sakura_core/Makefile
  sakura_core/StdAfx.h
  sakura_lang_en_US/Makefile
  sakura_lang_en_US/sakura_lang_en_US.vcxproj
Labels: MinGW, refactoring

#548 ターゲットwindowsをwindows7に上げる
  resource/cursor_hand.cur
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/CSelectLang.cpp
  sakura_core/Makefile
  sakura_core/_main/CProcessFactory.cpp
  sakura_core/_main/WinMain.cpp
  sakura_core/_os/COsVersionInfo.cpp
  sakura_core/_os/COsVersionInfo.h
  sakura_core/apiwrap/StdApi.cpp
  sakura_core/apiwrap/StdApi.h
  sakura_core/basis/primitive.h
  sakura_core/cmd/CViewCommander_Edit_advanced.cpp
  sakura_core/cmd/CViewCommander_TagJump.cpp
  sakura_core/config/system_constants.h
  sakura_core/dlg/CDlgFavorite.cpp
  sakura_core/dlg/CDlgOpenFile.cpp
  sakura_core/env/CFileNameManager.cpp
  sakura_core/extmodule/CHtmlHelp.cpp
  sakura_core/extmodule/CHtmlHelp.h
  sakura_core/func/Funccode.h
  sakura_core/print/CPrintPreview.cpp
  sakura_core/sakura_rc.rc
  sakura_core/uiparts/CMenuDrawer.cpp
  sakura_core/uiparts/CMenuDrawer.h
  sakura_core/uiparts/HandCursor.h
  sakura_core/util/os.h
  sakura_core/util/shell.cpp
  sakura_core/util/std_macro.h
  sakura_core/util/window.h
  sakura_core/view/CEditView.cpp
  sakura_core/view/CEditView.h
  sakura_core/view/CEditView_Diff.cpp
  sakura_core/view/CEditView_ExecCmd.cpp
  sakura_core/view/CEditView_Mouse.cpp
  sakura_core/window/CEditWnd.cpp
  sakura_core/window/CEditWnd.h
  sakura_core/window/CTabWnd.cpp
  sakura_lang_en_US/Makefile
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement, refactoring

#555 sakura.hhの参照を変更
  help/sakura/sakura.hh
  help/sakura/sakura.hhp
Labels: document

#549 「ファイルの場所をエクスプローラーで開く」追加
  help/sakura/_RESOURCE/HLP000373.html
  help/sakura/sakura.hhc
  help/sakura/sakura.hhk
  help/sakura/sakura.hhp
  sakura_core/Funccode_x.hsrc
  sakura_core/cmd/CViewCommander.cpp
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/func/Funccode.cpp
  sakura_core/sakura.hh
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#571 ソリューションの clean/rebuild するのをやめて単にビルドする
  build-sln.bat
Labels: CI

#572 rmdir で削除対象のディレクトリパスをダブルクォートで囲む
  tests/create-project.bat
  zipArtifacts.bat
Labels: CI

#573 バッチファイルのヘルプの誤りを修正
  build-installer.bat
  build-sln.bat
  run-cppcheck.bat
  zipArtifacts.bat
Labels: CI

#564 doxygen コメントの @file をつける (take2)
  HeaderMake/HeaderMake.cpp
  sakura/githash.bat
  sakura_core/sakura.hh
Labels: CI, document

#574 マウスクリックによるキャレット移動が出来なくなる不具合の解消
  sakura_core/view/CEditView_Mouse.cpp
Labels: bug

#579 テストをコンパイル済みのエディタコードとリンクします。
  tests/create-project.bat
  tests/unittests/CMakeLists.txt
  tests/unittests/code-util_string_ex.cpp
Labels: CI, UnitTest

#583 Git hash 関連の環境変数をマクロ名に一致させる
  appveyor.md
  sakura/githash.bat
Labels: CI

#585 GIT_URL → GIT_REMOTE_ORIGIN_URL に名前変更
  appveyor.md
  sakura/githash.bat
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#587 すべてを含んだ zip を作成しないようにする (#514 の軽減策)
  README.md
  zipArtifacts.bat
Labels: CI
