Repository sakura-editor/sakura, pull requests merged in 2018-06, with the labels that each got.

#89 [x64対応] c4477 の警告を修正
  sakura_core/_os/CClipboard.cpp
  sakura_core/util/shell.cpp
Labels: x64

#95 [x64対応] MakefileMake に対する C4477 の警告修正
  MakefileMake/MakefileMake.cpp
Labels: x64

#96 appveyor で clone に失敗する件の対策 (軽減策)
  appveyor.yml
Labels: bug

#113 [x64対応] master の修正を x64 ブランチにマージする
  sakura/sakura.vcxproj
Labels: x64

#114 appveyor の成果物の zip 圧縮する
  appveyor.yml
  zipArtifacts.bat
Labels: CI

#94 dlg 配下のいくつかのファイルを UTF-8 (BOM付) に単純変換
  sakura_core/dlg/CDialog.cpp
  sakura_core/dlg/CDialog.h
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgAbout.h
  sakura_core/dlg/CDlgCancel.cpp
  sakura_core/dlg/CDlgCancel.h
  sakura_core/dlg/CDlgCompare.cpp
  sakura_core/dlg/CDlgCompare.h
  sakura_core/dlg/CDlgCtrlCode.h
  sakura_core/dlg/CDlgDiff.cpp
  sakura_core/dlg/CDlgDiff.h
  sakura_core/dlg/CDlgExec.cpp
  sakura_core/dlg/CDlgExec.h
  sakura_core/dlg/CDlgFavorite.cpp
  sakura_core/dlg/CDlgFavorite.h
  sakura_core/dlg/CDlgFileUpdateQuery.cpp
  sakura_core/dlg/CDlgFileUpdateQuery.h
  sakura_core/dlg/CDlgFind.cpp
  sakura_core/dlg/CDlgFind.h
  sakura_core/dlg/CDlgGrep.cpp
  sakura_core/dlg/CDlgGrep.h
  sakura_core/dlg/CDlgGrepReplace.cpp
  sakura_core/dlg/CDlgGrepReplace.h
  sakura_core/dlg/CDlgInput1.cpp
  sakura_core/dlg/CDlgInput1.h
  sakura_core/dlg/CDlgJump.cpp
  sakura_core/dlg/CDlgJump.h
  sakura_core/dlg/CDlgOpenFile.h
  sakura_core/dlg/CDlgPluginOption.h
  sakura_core/dlg/CDlgPrintSetting.cpp
  sakura_core/dlg/CDlgPrintSetting.h
  sakura_core/dlg/CDlgProfileMgr.cpp
  sakura_core/dlg/CDlgProfileMgr.h
  sakura_core/dlg/CDlgProperty.cpp
  sakura_core/dlg/CDlgProperty.h
  sakura_core/dlg/CDlgReplace.cpp
  sakura_core/dlg/CDlgReplace.h
  sakura_core/dlg/CDlgSetCharSet.cpp
  sakura_core/dlg/CDlgSetCharSet.h
  sakura_core/dlg/CDlgTagJumpList.cpp
  sakura_core/dlg/CDlgTagJumpList.h
  sakura_core/dlg/CDlgTagsMake.cpp
  sakura_core/dlg/CDlgTagsMake.h
  sakura_core/dlg/CDlgWinSize.cpp
  sakura_core/dlg/CDlgWinSize.h
  sakura_core/dlg/CDlgWindowList.cpp
  sakura_core/dlg/CDlgWindowList.h
Labels: refactoring

#147 SVN Revision 利用箇所を削除し、代わりに GitHash を用いる
  sakura_core/dlg/CDlgAbout.cpp
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: bug

#150 git情報が存在しないとき、バージョンダイアログにバージョン番号が表示されない＆文字化けする問題を修正
  sakura_core/dlg/CDlgAbout.cpp
Labels: bug

#156 appveyor で再起動したときにハングする問題の修正を試す
  appveyor.yml
Labels: CI, bug

#159 sakura_lang_en_US.dll のバージョンにGitHash が含まれない
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: bug

#163 solution のビルドをバッチファイルの中で行う
  appveyor.yml
  build-sln.bat
Labels: CI, refactoring

#158 Git remote URL をバージョン情報に含める
  sakura/preBuild.bat
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgAbout.h
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: CI, enhancement

#144 appveyor でのインストーラビルド対応
  appveyor.yml
  build-installer.bat
  installer/sakura.iss
  zipArtifacts.bat
Labels: CI, installer

#130 Windows10メニュー対応
  installer/sakura.iss
Labels: installer

#161 [x64対応] master の修正を x64 ブランチにマージする
  .gitattributes
  appveyor.yml
  build-chm.bat
  build-installer.bat
  build-sln.bat
  installer/externals/bregonig/bron412.zip
  installer/externals/bregonig/readme.txt
  installer/externals/readme.txt
  installer/sakura.iss
  sakura/preBuild.bat
  sakura_core/CGrepAgent.cpp
  sakura_core/CGrepAgent.h
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgAbout.h
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
  zipArtifacts.bat
Labels: x64

#170 sakura.iss を UTF8 に変更
  installer/sakura.iss
Labels: installer, refactoring

#169 appveyor の成果物をダウンロードしてエクスプローラで解凍して実行すると警告が出る
  README.md
  installer/warning.txt
  zipArtifacts.bat
Labels: CI, document, installer

#171 solution のビルド用のバッチファイル修正
  appveyor.yml
  build-sln.bat
Labels: CI, refactoring

#176 innosetup-5.6.1-unicode.exe 対応
  installer/sakura.iss
Labels: CI, installer

#178 インストーラのバージョンを設定
  installer/sakura.iss
Labels: CI, installer

#173 x64 の artifacts に alpha とつける
  README.md
  appveyor.yml
  installer/warning-alpha.txt
  zipArtifacts.bat
Labels: CI, x64

#182 [x64] x64 版でバージョン情報にアルファ版の表示を行う (再作成)
  sakura_core/config/app_constants.h
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/version.h
Labels: x64

#86 x64 作業集約場所：2018-06-27 をもって master に統合する
  .gitignore
  MakefileMake/MakefileMake.cpp
  appveyor.yml
  sakura.sln
  sakura/.gitignore
  sakura/preBuild.bat
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/_os/CClipboard.cpp
  sakura_core/config/app_constants.h
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/sakura_rc.rc
  sakura_core/util/shell.cpp
  sakura_core/version.h
  sakura_lang_en_US/.gitignore
  sakura_lang_en_US/sakura_lang.h
  sakura_lang_en_US/sakura_lang_en_US.vcxproj
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: IMPORTANT, x64

#177 appveyor のビルドリンクをバージョン情報に追加
  sakura/preBuild.bat
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgAbout.h
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: CI, enhancement

#180 Installer のx64 対応
  build-installer.bat
  installer/sakura-Win32.iss
  installer/sakura-common.iss
  installer/sakura-x64.iss
Labels: installer, x64

#187 gitrev.h を artifacts に含める
  zipArtifacts.bat
Labels: CI

#175 一つのバッチファイルですべてのビルド～archive 作成まで行うようにする。
  appveyor.yml
  build-all.bat
Labels: CI

#188 gitrev.h から githash.h に名前変更
  sakura/preBuild.bat
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/.gitignore
  sakura_core/version.h
  zipArtifacts.bat
Labels: refactoring

#191 Git情報がなくてもビルドできるようにする (Close #148)
  sakura_core/version.h
Labels: bug

#190 sha256 を計算して、計算結果を成果物に含める
  calc-hash.bat
  calc-hash.py
  zipArtifacts.bat
Labels: CI

#195 バージョン定義を一箇所で定義する
  sakura_core/sakura_rc.rc
  sakura_core/version.h
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#197 mem 配下のいくつかのファイルを UTF-8 (BOM付) に単純変換
  sakura_core/mem/CMemory.cpp
  sakura_core/mem/CMemory.h
  sakura_core/mem/CMemoryIterator.h
  sakura_core/mem/CNative.cpp
  sakura_core/mem/CNative.h
  sakura_core/mem/CNativeA.h
  sakura_core/mem/CNativeT.h
  sakura_core/mem/CNativeW.cpp
  sakura_core/mem/CNativeW.h
  sakura_core/mem/CRecycledBuffer.cpp
  sakura_core/mem/CRecycledBuffer.h
Labels: refactoring
