Repository sakura-editor/sakura, pull requests merged in 2018-09, with the labels that each got.

#396 非推奨テンプレートstd::auto_ptrを一括置換する
  sakura_core/CGrepAgent.cpp
  sakura_core/CPropertyManager.cpp
  sakura_core/CWriteManager.cpp
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/convert/CConvert.cpp
  sakura_core/dlg/CDlgOpenFile.cpp
  sakura_core/dlg/CDlgPluginOption.cpp
  sakura_core/dlg/CDlgTagJumpList.cpp
  sakura_core/typeprop/CDlgTypeList.cpp
  sakura_core/view/CEditView_ExecCmd.cpp
Labels: refactoring

#402 インストーラに perl_license.txt と perl_license_jp.txt を同梱する
  installer/sakura-common.iss
Labels: CI, document, installer, license

#383 HTML Help 中のリンクを GitHub のものに変える
  help/plugin/Text/index.html
  help/sakura/_RESOURCE/HLP000001.html
  help/sakura/_RESOURCE/HLP000104.html
  help/sakura/_RESOURCE/HLP000112.html
  help/sakura/_RESOURCE/HLP_UR000.html
Labels: document

#405 コメントの修正
  sakura_core/CKeyWordSetMgr.cpp
  sakura_core/_main/CNormalProcess.cpp
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/cmd/CViewCommander_Macro.cpp
  sakura_core/doc/CDocReader.cpp
  sakura_core/plugin/CWSHPlugin.cpp
Labels: document

#399 Program Files や Program Files (x86) のパスを決め打ちせずに環境変数を参照する
  build-chm.bat
  build-installer.bat
  build-sln.bat
  run-cppcheck.bat
  tools/CppCheck/find-CppCheck.bat
  tools/CppCheck/readme.md
  tools/ISCC/find-ISCC.bat
  tools/ISCC/readme.md
  tools/hhc/find-hhc.bat
  tools/hhc/readme.md
  tools/msbuild/find-msbuild.bat
  tools/msbuild/readme.md
  tools/zip/find-7z.bat
  tools/zip/listzip.bat
  tools/zip/unzip.bat
  tools/zip/zip.bat
Labels: CI

#404 auto_array_ptr を廃止して std::unique_ptr に置き換え
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/CGrepAgent.cpp
  sakura_core/CHokanMgr.cpp
  sakura_core/Makefile
  sakura_core/doc/CDocOutline.cpp
  sakura_core/doc/CEditDoc.cpp
  sakura_core/macro/CWSHIfObj.cpp
  sakura_core/typeprop/CImpExpManager.cpp
  sakura_core/typeprop/CPropTypesRegex.cpp
  sakura_core/util/other_util.cpp
  sakura_core/util/other_util.h
Labels: refactoring

#415 タスクトレイのメニュー項目のデバッグ方法 に関するドキュメントを追加
  README.md
  debug-tasktray-menu.md
Labels: document

#422 単体テストのプロジェクト設定で sakura editor 本体のソースコードのインクルードディレクトリの指定を追加する
  tests/unittests/CMakeLists.txt
  unittest.md
Labels: UnitTest

#407 MinGW Makefileをデバッグ/リリース両対応にする
  sakura_core/Makefile
Labels: MinGW

#435 単体テスト向けの CMakeLists.txt で Visual Studio のスタートアッププロジェクトの設定
  tests/CMakeLists.txt
Labels: UnitTest

#436 README にカンバンリンクを追加
  README.md
Labels: document

#421 メールアドレスの色替え判定を高速化すると同時にRFCに準拠させる
  sakura_core/parse/CWordParse.cpp
  sakura_core/parse/CWordParse.h
  sakura_core/util/string_ex.cpp
  sakura_core/util/string_ex.h
  sakura_core/view/CEditView.cpp
  sakura_core/view/CEditView_Mouse.cpp
  sakura_core/view/colors/CColor_Url.cpp
  tests/unittests/CMakeLists.txt
  tests/unittests/code-IsMailAddress_20160427.cpp
  tests/unittests/code-util_string_ex.cpp
  tests/unittests/test-is_mailaddress.cpp
Labels: enhancement, specification change, speed up

#449 バージョンダイアログの "Share Ver" 表記を削除する
  sakura_core/dlg/CDlgAbout.cpp
Labels: specification change

#462 README.md にダウンロード数のバッチを追加する
  README.md
Labels: document

#456 ツールバーの状態更新を必要な場合にのみ行うように変更
  sakura_core/apiwrap/CommonControl.h
  sakura_core/window/CMainToolBar.cpp
Labels: speed up

#460 IME編集エリアの位置変更を行う ImmSetCompositionWindow の呼び出しは IMEが開いている時だけに限定
  sakura_core/view/CEditView_Ime.cpp
Labels: speed up

#453 SetScrollInfo の呼び出しを抑制
  sakura_core/view/CEditView_Scroll.cpp
Labels: speed up

#359 インストーラの UI を英語対応にする
  installer/instmaterials/info.txt
  installer/instmaterials/info_us.txt
  installer/sakura-common.iss
Labels: Internationalization, installer

#470 LICENSEファイルを追加する
  LICENSE
Labels: document, license

#386 deleteのオーバーロードがGCCに怒られる対応
  sakura_core/config/build_config.cpp
  sakura_core/config/build_config.h
Labels: MinGW

#479 PR #478 の不備修正
  checkEncoding.py
Labels: CI, IMPORTANT, bug

#483 インストーラのビルドログをファイルに出力する
  build-installer.bat
  zipArtifacts.bat
Labels: installer

#482 appveyorでロケール設定するのをやめる
  HeaderMake/HeaderMake.cpp
  MakefileMake/MakefileMake.cpp
  appveyor.yml
  sakura/sakura.vcxproj
  sakura_core/Funccode_x.hsrc
Labels: CI, speed up

#484 実行ファイルと インストーラを別のZIPに分離する
  README.md
  zipArtifacts.bat
Labels: CI

#411 『SAKURAで Grep』をエクスプローラに追加する
  installer/sakura-common.iss
Labels: enhancement, installer

#495 ヘッダのプロトタイプ宣言で明示的に変数名を指定する
  sakura_core/CHokanMgr.h
  sakura_core/CKeyWordSetMgr.h
  sakura_core/_main/CControlTray.h
  sakura_core/_main/CNormalProcess.h
  sakura_core/_main/CProcessFactory.h
  sakura_core/_os/CDropTarget.h
  sakura_core/charset/charcode.h
  sakura_core/cmd/CViewCommander.h
  sakura_core/dlg/CDialog.h
  sakura_core/dlg/CDlgAbout.h
  sakura_core/dlg/CDlgCancel.h
  sakura_core/dlg/CDlgCompare.h
  sakura_core/dlg/CDlgCtrlCode.h
  sakura_core/dlg/CDlgDiff.h
  sakura_core/dlg/CDlgExec.h
  sakura_core/dlg/CDlgFavorite.h
  sakura_core/dlg/CDlgFind.h
  sakura_core/dlg/CDlgGrep.h
  sakura_core/dlg/CDlgGrepReplace.h
  sakura_core/dlg/CDlgInput1.h
  sakura_core/dlg/CDlgJump.h
  sakura_core/dlg/CDlgPluginOption.h
  sakura_core/dlg/CDlgPrintSetting.h
  sakura_core/dlg/CDlgProfileMgr.h
  sakura_core/dlg/CDlgProperty.h
  sakura_core/dlg/CDlgReplace.h
  sakura_core/dlg/CDlgSetCharSet.h
  sakura_core/dlg/CDlgTagJumpList.h
  sakura_core/dlg/CDlgTagsMake.h
  sakura_core/dlg/CDlgWinSize.h
  sakura_core/dlg/CDlgWindowList.h
  sakura_core/doc/CEditDoc.h
  sakura_core/doc/layout/CLayoutMgr.h
  sakura_core/env/CAppNodeManager.h
  sakura_core/func/CFuncKeyWnd.h
  sakura_core/io/CFileLoad.h
  sakura_core/macro/CMacroFactory.h
  sakura_core/mem/CMemory.h
  sakura_core/mem/CNativeA.h
  sakura_core/outline/CDlgFileTree.h
  sakura_core/outline/CDlgFuncList.h
  sakura_core/print/CPrint.h
  sakura_core/print/CPrintPreview.h
  sakura_core/prop/CPropCommon.h
  sakura_core/typeprop/CDlgKeywordSelect.h
  sakura_core/typeprop/CDlgTypeAscertain.h
  sakura_core/typeprop/CDlgTypeList.h
  sakura_core/typeprop/CImpExpManager.h
  sakura_core/typeprop/CPropTypes.h
  sakura_core/util/window.h
  sakura_core/view/CCaret.h
  sakura_core/view/CEditView.h
  sakura_core/window/CAutoScrollWnd.h
  sakura_core/window/CEditWnd.h
  sakura_core/window/CSplitBoxWnd.h
  sakura_core/window/CSplitterWnd.h
  sakura_core/window/CTipWnd.h
Labels: refactoring

#491 インストーラのメニュー項目の表記を修正
  installer/sakura-common.iss
Labels: installer

#501 ヘッダのプロトタイプ宣言で明示的に変数名を指定する (CMemory)
  sakura_core/mem/CMemory.h
Labels: refactoring
