Repository sakura-editor/sakura, pull requests merged in 2018-08, with the labels that each got.

#318 リソースファイルのリファクタリング (複数行にわかれているのを一行にまとめる)
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#320 リソースファイルのリファクタリング (複数行にわかれているのを一行にまとめる)の対応漏れの対応
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#323 カンマの後ろの空白を1個に統一する
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#317 res ファイルのハッシュを計算するスクリプト
  calc-hash-res.py
Labels: enhancement

#324 バージョン番号の末尾をビルド番号にする
  sakura_core/version.h
Labels: CI, specification change

#315 英語表示したときの著作権表示でプログラム本体とリソースを別に表示する
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: license

#327 右クリックで表示される「SAKURAで開く(&E)」メニューにアイコンを設定する
  installer/sakura-common.iss
Labels: installer

#332 #329 によるデグレを修正 (bron412.zip の bregonig.dll が使われなくなる)
  build-installer.bat
Labels: installer

#333 インストーラの生成先のフォルダにプラットフォーム名を含める
  build-installer.bat
  installer/sakura-Win32.iss
  installer/sakura-common.iss
  installer/sakura-x64.iss
  zipArtifacts.bat
Labels: installer

#336 postBuild.bat の処理内容を更新
  appveyor.md
Labels: document

#337 インストーラ用のドキュメントを更新
  README.md
  installer/readme.md
  installer/readme.txt
Labels: document

#340 keyword ディレクトリ以下のファイルの説明を追加
  installer/readme.md
Labels: document

#339 markdown のスペルミス修正
  appveyor.md
  unittest.md
Labels: document

#335 bregonig.dll のファイル内容とタイムスタンプを比較する
  build-installer.bat
Labels: installer

#341 ビルドに関するドキュメントを更新、SKIP_CREATE_GITHASH に関する説明を移動
  README.md
  build.md
  installer/readme.md
Labels: document

#347 リポジトリに直接 bregonig.dll を登録するのをやめてビルド時に zip を解凍して成果物に含める
  README.md
  appveyor.md
  build-installer.bat
  build.md
  installer/externals/bregonig/Win32/bregonig.dll
  installer/externals/bregonig/x64/bregonig.dll
  installer/readme.md
  sakura/postBuild.bat
Labels: CI

#350 7z.exe による zip ファイル処理と powershell による zip ファイル処理に両対応する
  appveyor.md
  build.md
  sakura/postBuild.bat
  tools/zip/find-7z.bat
  tools/zip/listzip.bat
  tools/zip/listzip.ps1
  tools/zip/readme.md
  tools/zip/unzip.bat
  tools/zip/unzip.ps1
  tools/zip/zip.bat
  tools/zip/zip.ps1
  zipArtifacts.bat
Labels: CI

#353 markdown で成果物のダウンロード方法が実態にあっていないのを修正
  README.md
Labels: CI, document

#354 警告を解析して excel ファイルに出力する処理で同一の警告を一つのシートにまとめて出力する
  parse-buildlog.py
Labels: CI

#355 Appveyor 関連の環境変数をバッチファイルの形で保存する
  appveyor_env.py
  zipArtifacts.bat
Labels: CI

#363 MINGW_HAS_SECURE_APIが無効か判定する式の修正
  sakura_core/util/string_ex.cpp
  sakura_core/util/string_ex.h
Labels: MinGW

#364 cppcheck の出力 xml ファイルに platform 名や configuration 名を追加
  .gitignore
  run-cppcheck.bat
  zipArtifacts.bat
Labels: CI

#375 run-cppcheck.bat をリファクタリングする
  run-cppcheck.bat
Labels: cppcheck, refactoring

#377 cppcheck の標準出力をリダイレクトしてファイルに落とす
  run-cppcheck.bat
  zipArtifacts.bat
Labels: CI, cppcheck
