Repository sakura-editor/sakura, pull requests merged in 2018-07, with the labels that each got.

#201 サポートリンク等の情報を GitHub ベースのものに変更する
  installer/sakura-common.iss
Labels: installer

#203 ALPHA_VERSION の定義を build_config.h に移動して version.h の依存関係を減らす
  sakura_core/config/app_constants.h
  sakura_core/config/build_config.h
  sakura_core/version.h
Labels: refactoring

#199 artifacts のファイル名、フォルダ名に各種情報をつける
  zipArtifacts.bat
Labels: CI

#207 x64 のビルド警告を修正する準備のために発生している警告を csv にまとめる
  build-sln.bat
  parse-buildlog.bat
  parse-buildlog.py
  zipArtifacts.bat
Labels: CI, x64

#210 GitHub の commit に対する URL, PR の Head commit に対する URL へのリンクをバージョンダイアログに追加
  sakura/preBuild.bat
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgAbout.h
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: CI, enhancement

#218 msbuild-xxx-xxx.log に含まれる Warning が重複して含まれるために、csv の結果も重複して含まれる問題に対する workaround
  parse-buildlog.py
Labels: CI

#219 githash.h で定義されないマクロに対して代わりにコメントを出力する
  sakura/preBuild.bat
Labels: CI, enhancement

#221 githash.h の末尾の空白を削除する
  sakura/preBuild.bat
  sakura/removeTailSpace.bat
Labels: CI

#204 HeaderMake と MakefileMake の出力先を変える
  HeaderMake/HeaderMake.vcxproj
  MakefileMake/MakefileMake.vcxproj
  sakura/preBuild.bat
  sakura/sakura.vcxproj
Labels: refactoring

#226 githash.h の末尾の空白を削除する (sed不使用版)
  sakura/preBuild.bat
  sakura/removeTailSpace.bat
Labels: refactoring

#222 ビルドログの解析スクリプトをリファクタリング
  parse-buildlog.py
Labels: CI, refactoring

#229 ログを別の ZIP に artifacts として含める
  zipArtifacts.bat
Labels: CI

#228 [リファクタリング] APPVEYOR_BUILD_URL を preBuild.bat で生成する
  sakura/preBuild.bat
  sakura_core/dlg/CDlgAbout.cpp
Labels: CI, refactoring

#231 Win32 の artifacts に HeaderMake.exe と MakefileMake.exe を含めないようにする
  zipArtifacts.bat
Labels: CI

#232 copyright を 2018 に変更
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: license

#234 artifacts の名前に appveyor の名前を含める (構成要素の順序調整)
  appveyor.yml
  zipArtifacts.bat
Labels: CI

#238 msbuild のログファイルの解析結果を excel ファイルに変換して artifacts に含める
  parse-buildlog.bat
  parse-buildlog.py
  zipArtifacts.bat
Labels: CI

#125 ファイル読み込みとgrepの高速化
  sakura_core/CGrepAgent.cpp
  sakura_core/CGrepAgent.h
  sakura_core/charset/CESI.cpp
  sakura_core/charset/CShiftJis.cpp
  sakura_core/charset/CUtf8.cpp
Labels: speed up

#236 CGrepAgent::DoGrep のローカル変数初期化漏れ修正
  sakura_core/CGrepAgent.cpp
Labels: bug

#252 appveyor でのビルドの仕組みのドキュメントを追加
  README.md
  appveyor.md
Labels: CI, document

#255 markdown に TOC を追加
  README.md
  appveyor.md
Labels: document

#256 CI ビルドをスキップする方法について説明を追加
  appveyor.md
Labels: CI, document

#257 ビルドログの解析機能で Excel の出力を改善する
  .gitignore
  appveyor.md
  appveyor_env.py
  parse-buildlog.bat
  parse-buildlog.py
Labels: CI, document

#263 「ファイルの排他制御モード」のデフォルトを 「排他制御しない」に変更する
  sakura_core/env/CShareData.cpp
Labels: specification change

#251 リソースファイルのエンコーディングを UTF-8 (BOM無し) に変更
  sakura/sakura.vcxproj
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_en_US.vcxproj
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#267 テキストの折り返し方法のデフォルトを 「折り返さない」に変更
  sakura_core/types/CType.cpp
Labels: specification change

#294 エントリをProfileへ書き込む処理（CProfile::SetProfileDataImp）に入れてしまった不具合の修正
  sakura_core/CProfile.cpp
Labels: bug

#290 アセンブラ出力を行い、artifacts に含める
  sakura/sakura.vcxproj
  zipArtifacts.bat
Labels: CI, enhancement

#265 debug 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/debug/CRunningTimer.cpp
  sakura_core/debug/CRunningTimer.h
  sakura_core/debug/Debug1.cpp
  sakura_core/debug/Debug1.h
  sakura_core/debug/Debug2.cpp
  sakura_core/debug/Debug2.h
  sakura_core/debug/Debug3.cpp
  sakura_core/debug/Debug3.h
Labels: refactoring

#268 docplus 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/docplus/CBookmarkManager.cpp
  sakura_core/docplus/CBookmarkManager.h
  sakura_core/docplus/CDiffManager.cpp
  sakura_core/docplus/CDiffManager.h
  sakura_core/docplus/CFuncListManager.cpp
  sakura_core/docplus/CFuncListManager.h
  sakura_core/docplus/CModifyManager.cpp
  sakura_core/docplus/CModifyManager.h
Labels: refactoring

#269 env 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/env/CAppNodeManager.cpp
  sakura_core/env/CAppNodeManager.h
  sakura_core/env/CDocTypeManager.cpp
  sakura_core/env/CDocTypeManager.h
  sakura_core/env/CFileNameManager.cpp
  sakura_core/env/CFileNameManager.h
  sakura_core/env/CFormatManager.cpp
  sakura_core/env/CFormatManager.h
  sakura_core/env/CHelpManager.cpp
  sakura_core/env/CHelpManager.h
  sakura_core/env/CSakuraEnvironment.cpp
  sakura_core/env/CSakuraEnvironment.h
  sakura_core/env/CSearchKeywordManager.cpp
  sakura_core/env/CSearchKeywordManager.h
  sakura_core/env/CShareData.cpp
  sakura_core/env/CShareData.h
  sakura_core/env/CShareData_IO.cpp
  sakura_core/env/CShareData_IO.h
  sakura_core/env/CTagJumpManager.cpp
  sakura_core/env/CTagJumpManager.h
  sakura_core/env/CommonSetting.cpp
  sakura_core/env/CommonSetting.h
  sakura_core/env/DLLSHAREDATA.cpp
  sakura_core/env/DLLSHAREDATA.h
Labels: refactoring

#270 extmodule 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/extmodule/CBregexp.cpp
  sakura_core/extmodule/CBregexp.h
  sakura_core/extmodule/CBregexpDll2.cpp
  sakura_core/extmodule/CBregexpDll2.h
  sakura_core/extmodule/CDllHandler.cpp
  sakura_core/extmodule/CDllHandler.h
  sakura_core/extmodule/CHtmlHelp.cpp
  sakura_core/extmodule/CHtmlHelp.h
  sakura_core/extmodule/CMigemo.cpp
  sakura_core/extmodule/CMigemo.h
  sakura_core/extmodule/CUxTheme.cpp
  sakura_core/extmodule/CUxTheme.h
Labels: refactoring

#266 doc 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/doc/CBlockComment.cpp
  sakura_core/doc/CBlockComment.h
  sakura_core/doc/CDocEditor.cpp
  sakura_core/doc/CDocEditor.h
  sakura_core/doc/CDocFile.cpp
  sakura_core/doc/CDocFile.h
  sakura_core/doc/CDocFileOperation.cpp
  sakura_core/doc/CDocFileOperation.h
  sakura_core/doc/CDocListener.cpp
  sakura_core/doc/CDocListener.h
  sakura_core/doc/CDocLocker.cpp
  sakura_core/doc/CDocLocker.h
  sakura_core/doc/CDocOutline.cpp
  sakura_core/doc/CDocOutline.h
  sakura_core/doc/CDocReader.cpp
  sakura_core/doc/CDocReader.h
  sakura_core/doc/CDocType.cpp
  sakura_core/doc/CDocType.h
  sakura_core/doc/CDocTypeSetting.cpp
  sakura_core/doc/CDocTypeSetting.h
  sakura_core/doc/CDocVisitor.cpp
  sakura_core/doc/CDocVisitor.h
  sakura_core/doc/CEditDoc.cpp
  sakura_core/doc/CEditDoc.h
  sakura_core/doc/CLineComment.cpp
  sakura_core/doc/CLineComment.h
  sakura_core/doc/layout/CLayout.cpp
  sakura_core/doc/layout/CLayout.h
  sakura_core/doc/layout/CLayoutExInfo.h
  sakura_core/doc/layout/CLayoutMgr.cpp
  sakura_core/doc/layout/CLayoutMgr.h
  sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
  sakura_core/doc/layout/CLayoutMgr_New.cpp
  sakura_core/doc/layout/CLayoutMgr_New2.cpp
  sakura_core/doc/layout/CTsvModeInfo.cpp
  sakura_core/doc/layout/CTsvModeInfo.h
  sakura_core/doc/logic/CDocLine.cpp
  sakura_core/doc/logic/CDocLine.h
  sakura_core/doc/logic/CDocLineMgr.cpp
  sakura_core/doc/logic/CDocLineMgr.h
Labels: refactoring

#271 func 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/func/CFuncKeyWnd.cpp
  sakura_core/func/CFuncKeyWnd.h
  sakura_core/func/CFuncLookup.cpp
  sakura_core/func/CFuncLookup.h
  sakura_core/func/CKeyBind.cpp
  sakura_core/func/CKeyBind.h
  sakura_core/func/Funccode.cpp
  sakura_core/func/Funccode.h
Labels: refactoring

#272 mfclike 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/mfclike/CMyWnd.cpp
  sakura_core/mfclike/CMyWnd.h
Labels: refactoring

#273 outline 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/outline/CDlgFileTree.cpp
  sakura_core/outline/CDlgFileTree.h
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/outline/CDlgFuncList.h
  sakura_core/outline/CFuncInfo.cpp
  sakura_core/outline/CFuncInfo.h
  sakura_core/outline/CFuncInfoArr.cpp
  sakura_core/outline/CFuncInfoArr.h
Labels: refactoring

#274 parse 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/parse/CWordParse.cpp
  sakura_core/parse/CWordParse.h
Labels: refactoring

#275 plugin 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/plugin/CComplementIfObj.h
  sakura_core/plugin/CDllPlugin.cpp
  sakura_core/plugin/CDllPlugin.h
  sakura_core/plugin/CJackManager.cpp
  sakura_core/plugin/CJackManager.h
  sakura_core/plugin/COutlineIfObj.h
  sakura_core/plugin/CPlugin.cpp
  sakura_core/plugin/CPlugin.h
  sakura_core/plugin/CPluginIfObj.h
  sakura_core/plugin/CPluginManager.cpp
  sakura_core/plugin/CPluginManager.h
  sakura_core/plugin/CSmartIndentIfObj.h
  sakura_core/plugin/CWSHPlugin.cpp
  sakura_core/plugin/CWSHPlugin.h
Labels: refactoring

#276 print 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/print/CPrint.cpp
  sakura_core/print/CPrint.h
  sakura_core/print/CPrintPreview.cpp
  sakura_core/print/CPrintPreview.h
Labels: refactoring

#277 prop 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/prop/CPropComBackup.cpp
  sakura_core/prop/CPropComCustmenu.cpp
  sakura_core/prop/CPropComEdit.cpp
  sakura_core/prop/CPropComFile.cpp
  sakura_core/prop/CPropComFileName.cpp
  sakura_core/prop/CPropComFormat.cpp
  sakura_core/prop/CPropComGeneral.cpp
  sakura_core/prop/CPropComGrep.cpp
  sakura_core/prop/CPropComHelper.cpp
  sakura_core/prop/CPropComKeybind.cpp
  sakura_core/prop/CPropComKeyword.cpp
  sakura_core/prop/CPropComMacro.cpp
  sakura_core/prop/CPropComMainMenu.cpp
  sakura_core/prop/CPropComPlugin.cpp
  sakura_core/prop/CPropComStatusbar.cpp
  sakura_core/prop/CPropComTab.cpp
  sakura_core/prop/CPropComToolbar.cpp
  sakura_core/prop/CPropComWin.cpp
  sakura_core/prop/CPropCommon.cpp
  sakura_core/prop/CPropCommon.h
Labels: refactoring

#278 recent 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/recent/CMRUFile.cpp
  sakura_core/recent/CMRUFile.h
  sakura_core/recent/CMRUFolder.cpp
  sakura_core/recent/CMRUFolder.h
  sakura_core/recent/CMruListener.cpp
  sakura_core/recent/CMruListener.h
  sakura_core/recent/CRecent.cpp
  sakura_core/recent/CRecent.h
  sakura_core/recent/CRecentCmd.cpp
  sakura_core/recent/CRecentCmd.h
  sakura_core/recent/CRecentCurDir.cpp
  sakura_core/recent/CRecentCurDir.h
  sakura_core/recent/CRecentEditNode.cpp
  sakura_core/recent/CRecentEditNode.h
  sakura_core/recent/CRecentExceptMru.cpp
  sakura_core/recent/CRecentExceptMru.h
  sakura_core/recent/CRecentFile.cpp
  sakura_core/recent/CRecentFile.h
  sakura_core/recent/CRecentFolder.cpp
  sakura_core/recent/CRecentFolder.h
  sakura_core/recent/CRecentGrepFile.cpp
  sakura_core/recent/CRecentGrepFile.h
  sakura_core/recent/CRecentGrepFolder.cpp
  sakura_core/recent/CRecentGrepFolder.h
  sakura_core/recent/CRecentImp.cpp
  sakura_core/recent/CRecentImp.h
  sakura_core/recent/CRecentReplace.cpp
  sakura_core/recent/CRecentReplace.h
  sakura_core/recent/CRecentSearch.cpp
  sakura_core/recent/CRecentSearch.h
  sakura_core/recent/CRecentTagjumpKeyword.cpp
  sakura_core/recent/CRecentTagjumpKeyword.h
  sakura_core/recent/SShare_History.h
Labels: refactoring

#279 typeprop 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/typeprop/CDlgKeywordSelect.cpp
  sakura_core/typeprop/CDlgKeywordSelect.h
  sakura_core/typeprop/CDlgSameColor.cpp
  sakura_core/typeprop/CDlgSameColor.h
  sakura_core/typeprop/CDlgTypeAscertain.cpp
  sakura_core/typeprop/CDlgTypeAscertain.h
  sakura_core/typeprop/CDlgTypeList.cpp
  sakura_core/typeprop/CDlgTypeList.h
  sakura_core/typeprop/CImpExpManager.cpp
  sakura_core/typeprop/CImpExpManager.h
  sakura_core/typeprop/CPropTypes.cpp
  sakura_core/typeprop/CPropTypes.h
  sakura_core/typeprop/CPropTypesColor.cpp
  sakura_core/typeprop/CPropTypesKeyHelp.cpp
  sakura_core/typeprop/CPropTypesRegex.cpp
  sakura_core/typeprop/CPropTypesScreen.cpp
  sakura_core/typeprop/CPropTypesSupport.cpp
  sakura_core/typeprop/CPropTypesWindow.cpp
Labels: refactoring

#280 types 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/types/CType.cpp
  sakura_core/types/CType.h
  sakura_core/types/CTypeSupport.cpp
  sakura_core/types/CTypeSupport.h
  sakura_core/types/CType_Asm.cpp
  sakura_core/types/CType_Awk.cpp
  sakura_core/types/CType_Basis.cpp
  sakura_core/types/CType_Cobol.cpp
  sakura_core/types/CType_CorbaIdl.cpp
  sakura_core/types/CType_Cpp.cpp
  sakura_core/types/CType_Dos.cpp
  sakura_core/types/CType_Erlang.cpp
  sakura_core/types/CType_Html.cpp
  sakura_core/types/CType_Ini.cpp
  sakura_core/types/CType_Java.cpp
  sakura_core/types/CType_Others.cpp
  sakura_core/types/CType_Pascal.cpp
  sakura_core/types/CType_Perl.cpp
  sakura_core/types/CType_Python.cpp
  sakura_core/types/CType_Rich.cpp
  sakura_core/types/CType_Sql.cpp
  sakura_core/types/CType_Tex.cpp
  sakura_core/types/CType_Text.cpp
  sakura_core/types/CType_Vb.cpp
Labels: refactoring

#281 uiparts 配下のファイルを UTF-8 (BOM付) に変換
  sakura_core/uiparts/CGraphics.cpp
  sakura_core/uiparts/CGraphics.h
  sakura_core/uiparts/CImageListMgr.cpp
  sakura_core/uiparts/CImageListMgr.h
  sakura_core/uiparts/CMenuDrawer.cpp
  sakura_core/uiparts/CMenuDrawer.h
  sakura_core/uiparts/CSoundSet.cpp
  sakura_core/uiparts/CSoundSet.h
  sakura_core/uiparts/CVisualProgress.cpp
  sakura_core/uiparts/CVisualProgress.h
  sakura_core/uiparts/CWaitCursor.cpp
  sakura_core/uiparts/CWaitCursor.h
  sakura_core/uiparts/HandCursor.h
Labels: refactoring

#284 window 配下のファイルを UTF-8 (BOM付) に変更
  sakura_core/window/CAutoScrollWnd.cpp
  sakura_core/window/CAutoScrollWnd.h
  sakura_core/window/CEditWnd.cpp
  sakura_core/window/CEditWnd.h
  sakura_core/window/CMainStatusBar.cpp
  sakura_core/window/CMainStatusBar.h
  sakura_core/window/CMainToolBar.cpp
  sakura_core/window/CMainToolBar.h
  sakura_core/window/CSplitBoxWnd.cpp
  sakura_core/window/CSplitBoxWnd.h
  sakura_core/window/CSplitterWnd.cpp
  sakura_core/window/CSplitterWnd.h
  sakura_core/window/CTabWnd.cpp
  sakura_core/window/CTabWnd.h
  sakura_core/window/CTipWnd.cpp
  sakura_core/window/CTipWnd.h
  sakura_core/window/CWnd.cpp
  sakura_core/window/CWnd.h
Labels: refactoring

#298 ログの警告の解析結果の CSV に blobURL を追加
  parse-buildlog.py
Labels: CI

#301 static で定義している変数を通常のローカル変数に変える
  sakura_core/debug/Debug2.cpp
Labels: bug

#303 CNativeA/CNativeW に対する AppendString のフォーマット書式対応版メソッドを準備
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/mem/CNativeA.cpp
  sakura_core/mem/CNativeA.h
  sakura_core/mem/CNativeW.cpp
  sakura_core/mem/CNativeW.h
Labels: refactoring

#310 preBuild.bat のリファクタリング
  sakura/funccode.bat
  sakura/gen-makefile.bat
  sakura/githash.bat
  sakura/preBuild.bat
Labels: CI, refactoring

#314 python のアウトライン解析を実装
  sakura_core/types/CType.cpp
  sakura_core/types/CType.h
  sakura_core/types/CType_Python.cpp
Labels: enhancement
