Repository sakura-editor/sakura, pull requests merged in 2018-11, with the labels that each got.

#596 Windows 10 でユーザーが手動でサクラエディタに対して関連付けを行えるようにする
  installer/sakura-common.iss
Labels: installer

#602 Windows 10 でユーザーが手動でサクラエディタに対して関連付けを行えるようにする (part2)
  installer/sakura-common.iss
Labels: installer

#591 Build and run tests on MinGW environment.
  sakura_core/Makefile
  tests/build-and-test.bat
  tests/create-project.bat
  tests/unittests/CMakeLists.txt
Labels: MinGW, UnitTest

#605 HTML Help で ビルドに必要な条件を更新
  help/sakura/_RESOURCE/HLP000112.html
Labels: document

#606 HTML Help でビルド方法に関する説明で build.md を参照するように変更
  help/sakura/_RESOURCE/HLP000112.html
Labels: document

#599 Windows 10 でのファイルの関連付けに関する説明を HTML Help に追加
  help/sakura/_RESOURCE/HLP000001.html
  help/sakura/_RESOURCE/HLP000374.html
  help/sakura/_RESOURCE/HLP000375.html
  help/sakura/_RESOURCE/images/FileAssoc-1-StartMenu.png
  help/sakura/_RESOURCE/images/FileAssoc-2-Setting.png
  help/sakura/_RESOURCE/images/FileAssoc-3-Application.png
  help/sakura/_RESOURCE/images/FileAssoc-4-DefaultApp.png
  help/sakura/_RESOURCE/images/FileAssoc-5-ChooseDefaultApp.png
  help/sakura/_RESOURCE/images/FileAssoc-6-ChooseDefaultApp.png
  help/sakura/_RESOURCE/images/FileAssoc-7-ChooseDefaultAppTxt.png
  help/sakura/_RESOURCE/images/FileAssoc-8-ChooseDefaultAppTxt.png
  help/sakura/_RESOURCE/images/FileAssoc-9-ChooseTxt-Sakura.png
  help/sakura/sakura.hhp
Labels: document

#580 AppVeyor のテストタブを利用します。
  tests/run-tests.bat
  tests/test_result_filter_tell_AppVeyor.bat
Labels: CI, UnitTest

#612 reST 用の拡張子 (.rst) を関連付け用の設定に追加
  installer/sakura-common.iss
Labels: installer

#603 コマンドプロンプトを開くためのメニューを実装
  help/sakura/_RESOURCE/HLP000376.html
  help/sakura/sakura.hhc
  help/sakura/sakura.hhk
  help/sakura/sakura.hhp
  sakura_core/Funccode_x.hsrc
  sakura_core/cmd/CViewCommander.cpp
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/func/Funccode.cpp
  sakura_core/sakura.hh
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#617 試行錯誤していたときの残骸を削除
  appveyor.yml
Labels: CI

#618 管理者としてコマンドプロンプトを開くメニュー項目を追加
  help/sakura/_RESOURCE/HLP000377.html
  help/sakura/sakura.hhc
  help/sakura/sakura.hhk
  help/sakura/sakura.hhp
  sakura_core/Funccode_x.hsrc
  sakura_core/cmd/CViewCommander.cpp
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/func/Funccode.cpp
  sakura_core/sakura.hh
  sakura_core/sakura_rc.rc
  sakura_core/util/os.cpp
  sakura_core/util/os.h
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#622 chm のビルドでリトライを実装
  build-chm.bat
Labels: CI

#627 `ファイルの場所を コマンドプロンプトを開く` で 管理者ではないときに 32bit アプリから 64bit OS上で起動したときに 32bit で起動してしまうのを修正
  sakura_core/cmd/CViewCommander_File.cpp
Labels: bug

#623 `ファイルの場所を powershell で開く` に対応する
  help/sakura/_RESOURCE/HLP000378.html
  help/sakura/_RESOURCE/HLP000379.html
  help/sakura/sakura.hhc
  help/sakura/sakura.hhk
  help/sakura/sakura.hhp
  sakura_core/Funccode_x.hsrc
  sakura_core/cmd/CViewCommander.cpp
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/func/Funccode.cpp
  sakura_core/sakura.hh
  sakura_core/sakura_rc.rc
  sakura_core/util/os.cpp
  sakura_core/util/os.h
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#635 doxygen の標準出力をファイルに保存して artifacts に含める
  run-doxygen.bat
  zipArtifacts.bat
Labels: CI, document, doxygen

#633 テストのディレクトリの誤りを修正 (単体テストが走らない件の対策としても有効)
  tests/run-tests.bat
Labels: CI, bug

#648 テストが全く実行されない場合に appveyor を失敗させる
  tests/run-tests.bat
Labels: CI, UnitTest

#651 doxygen の参考にならない警告を無効にします。WARN_IF_UNDOCUMENTED = NO
  doxygen.conf
Labels: CI, doxygen
