Repository sakura-editor/sakura, pull requests merged in 2018-12, with the labels that each got.

#657 スクロールバーの再描画を常には行わないように変更
  sakura_core/view/CEditView.h
  sakura_core/view/CEditView_Scroll.cpp
Labels: speed up

#660 縦スクロール時に不必要にルーラーの再描画がされないように対策
  sakura_core/view/CEditView_Scroll.cpp
Labels: speed up

#677 Fix: Make githash.h before doxygen.
  run-doxygen.bat
Labels: CI, bug

#683 Windows Imaging Component を使って背景画像を読み込み、透過描画対応
  sakura_core/Makefile
  sakura_core/doc/CEditDoc.cpp
  sakura_core/typeprop/CPropTypesWindow.cpp
  sakura_core/view/CEditView_Paint.cpp
  tests/unittests/CMakeLists.txt
Labels: enhancement

#680 コマンドアイコンの追加
  resource/mytool.bmp
  sakura_core/uiparts/CMenuDrawer.cpp
Labels: enhancement

#693 CodeFactor の badge を追加
  README.md
Labels: document

#700 `README.md` で `タスクトレイのメニュー項目をデバッグする方法` に変更
  README.md
  debug-tasktray-menu.md
Labels: document

#696 CHANGELOG.md の生成方法や取得方法を簡単に参照できるように markdown に説明を追加する
  README.md
Labels: document

#704 [拾い物です] 背景画像表示の不透明度を設定出来るように変更
  help/sakura/Cshelp.txt
  sakura_core/apiwrap/StdControl.h
  sakura_core/config/system_constants.h
  sakura_core/env/CShareData_IO.cpp
  sakura_core/sakura.hh
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_core/typeprop/CPropTypesWindow.cpp
  sakura_core/types/CType.cpp
  sakura_core/types/CType.h
  sakura_core/view/CEditView.h
  sakura_core/view/CEditView_Paint.cpp
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#705 Grep に関するメニューにショートカットを指定する
  installer/sakura-common.iss
Labels: installer

#604 UTF8 BOMなし を文字コードのデフォルトにする
  sakura_core/charset/charset.h
  sakura_core/types/CType.cpp
Labels: specification change

#710 GSTR_APPNAME の実体をグローバル変数に変える
  sakura_core/_main/WinMain.cpp
  sakura_core/config/app_constants.h
  sakura_core/typeprop/CImpExpManager.cpp
Labels: refactoring

#403 grep/grep 置換で除外ファイル、除外フォルダを指定できるようにする
  help/sakura/Cshelp.txt
  help/sakura/_RESOURCE/HLP000067.html
  help/sakura/_RESOURCE/HLP000362.html
  help/sakura/_RESOURCE/images/Grep.png
  help/sakura/_RESOURCE/images/GrepReplace.png
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/CGrepAgent.cpp
  sakura_core/CGrepAgent.h
  sakura_core/CGrepEnumKeys.h
  sakura_core/Makefile
  sakura_core/String_define.h
  sakura_core/_main/CCommandLine.h
  sakura_core/_main/CControlTray.cpp
  sakura_core/_main/CNormalProcess.cpp
  sakura_core/cmd/CViewCommander_Grep.cpp
  sakura_core/config/maxdata.h
  sakura_core/config/system_constants.h
  sakura_core/dlg/CDlgGrep.cpp
  sakura_core/dlg/CDlgGrep.h
  sakura_core/dlg/CDlgGrepReplace.cpp
  sakura_core/env/CSearchKeywordManager.cpp
  sakura_core/env/CSearchKeywordManager.h
  sakura_core/env/CShareData_IO.cpp
  sakura_core/recent/CRecentExcludeFile.cpp
  sakura_core/recent/CRecentExcludeFile.h
  sakura_core/recent/CRecentExcludeFolder.cpp
  sakura_core/recent/CRecentExcludeFolder.h
  sakura_core/recent/CRecentImp.h
  sakura_core/sakura.hh
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#713 バージョンを 2.4.0 の開発版に上げる
  sakura/githash.bat
  sakura_core/_main/WinMain.cpp
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/version.h
Labels: CI, management

#678 githash.bat の小改良
  sakura/githash.bat
Labels: refactoring

#723 CodeFactor の警告で localtime を使っているという警告を修正する
  sakura_core/CBackupAgent.cpp
Labels: CodeFactor

#729 Python3 でビルドログの解析に失敗するのを修正
  parse-buildlog.py
Labels: CI, bug

#730 (ビルドログの解析スクリプト) Python のバージョン判定処理をリファクタリング
  parse-buildlog.py
Labels: refactoring

#718 開いているファイルのフォルダのパスをクリップボードにコピーできるようにする
  README.md
  help/macro/macro.HHP
  help/macro/macro.hhc
  help/macro/macro.hhk
  help/macro/source/reference/clipboard/S_CopyDirPath.html
  help/macro/source/reference/clipboard/index.html
  help/macro/source/reference/index.html
  help/sakura/_RESOURCE/HLP000380.html
  help/sakura/sakura.hhc
  help/sakura/sakura.hhk
  help/sakura/sakura.hhp
  sakura_core/Funccode_x.hsrc
  sakura_core/cmd/CViewCommander.cpp
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_Clipboard.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/func/Funccode.cpp
  sakura_core/macro/CSMacroMgr.cpp
  sakura_core/sakura.hh
  sakura_core/sakura_rc.rc
  sakura_core/uiparts/CMenuDrawer.cpp
  sakura_lang_en_US/sakura_lang_rc.rc
  tools/macro/CopyDirPath/CopyDirPath.js
  tools/macro/CopyDirPath/CopyDirPath.mac
  tools/macro/CopyDirPath/CopyDirPath.vbs
  tools/macro/macro.md
Labels: enhancement

#739 ヘルプのバージョンを 2.4.0 に update (#713 に追従)
  help/sakura/_RESOURCE/HLP000001.html
Labels: document
