Repository sakura-editor/sakura, pull requests merged in 2019-08, with the labels that each got.

#978 REST通信をリトライさせる
  build-chm.bat
  help/extract-chm-from-artifact.ps1
Labels: CI, appveyor

#981 最新版msys2でビルドできるようにHeaderMakeを修正する
  HeaderMake/HeaderMake.cpp
Labels: CI, IMPORTANT, MinGW, appveyor

#955 cmake のパスを find-tools.bat で検索して cmake のパスが通っていなくてもビルドできるようにする
  tests/build-project.bat
  tests/create-project.bat
  tools/find-tools.bat
Labels: CI, appveyor, azure pipelines

#987 「すべて置換」処理の高速化
  sakura_core/cmd/CViewCommander_Search.cpp
Labels: speed up

#992 ファイル読み込み時のステータスバー上のプログレスバー更新やメッセージ配送処理の呼び出しは時間経過を契機に行う方式に変更
  sakura_core/CReadManager.cpp
Labels: speed up

#993 CViewSelect::PrintSelectionInfoMsg の高速化、及び行のEOL長を取得する処理の高速化
  sakura_core/CEol.cpp
  sakura_core/CEol.h
  sakura_core/view/CViewSelect.cpp
Labels: speed up

#985 メモリプールを使う事でメモリ確保と解放を高速化
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/doc/layout/CLayoutMgr.cpp
  sakura_core/doc/layout/CLayoutMgr.h
  sakura_core/doc/logic/CDocLineMgr.cpp
  sakura_core/doc/logic/CDocLineMgr.h
  sakura_core/mem/CPoolResource.h
Labels: speed up

#997 CImageListMgr::MyDitherBlt で DIB を使う事で最適化
  sakura_core/uiparts/CImageListMgr.cpp
Labels: speed up

#1004 文字列リテラルを格納する型の誤りを訂正
  sakura_core/cmd/CViewCommander_File.cpp
Labels: refactoring

#1005 C++規格で非推奨となった関数名を置換する
  sakura_core/CBackupAgent.cpp
  sakura_core/CKeyWordSetMgr.cpp
  sakura_core/CReadManager.cpp
  sakura_core/_main/CNormalProcess.cpp
  sakura_core/_os/CClipboard.cpp
  sakura_core/charset/CESI.cpp
  sakura_core/convert/convert_util2.h
  sakura_core/dlg/CDlgTagJumpList.cpp
  sakura_core/doc/CDocOutline.cpp
  sakura_core/env/CFileNameManager.cpp
  sakura_core/plugin/CPluginManager.cpp
  sakura_core/types/CType_Asm.cpp
  sakura_core/types/CType_Html.cpp
  sakura_core/types/CType_Sql.cpp
  sakura_core/types/CType_Vb.cpp
  sakura_core/util/file.cpp
  sakura_core/util/string_ex.cpp
  sakura_core/util/string_ex.h
  sakura_core/view/CEditView_Mouse.cpp
  sakura_core/view/CEditView_Search.cpp
Labels: refactoring

#1006 セキュリティに問題のあるCRT関数の使用を容認する
  sakura_core/StdAfx.h
Labels: refactoring

#1007 C++規格が変更されて非推奨となった関数名を置換する
  sakura_core/CDicMgr.cpp
  sakura_core/cmd/CViewCommander_Clipboard.cpp
  sakura_core/dlg/CDlgProfileMgr.cpp
  sakura_core/doc/CDocOutline.cpp
  sakura_core/docplus/CBookmarkManager.cpp
  sakura_core/env/CSakuraEnvironment.cpp
  sakura_core/func/CFuncLookup.cpp
  sakura_core/plugin/CPlugin.cpp
  sakura_core/typeprop/CImpExpManager.cpp
  sakura_core/util/tchar_printf.cpp
Labels: refactoring

#1009 変数のregister修飾を外す
  sakura_core/charset/CESI.cpp
  sakura_core/view/colors/CColor_Numeric.cpp
Labels: refactoring

#1008 Unicode版のみのサポートなので、不要なプリプロセッサ記述やコードを削除
  sakura_core/CDataProfile.h
  sakura_core/_main/WinMain.cpp
  sakura_core/_os/OleTypes.h
  sakura_core/apiwrap/StdApi.cpp
  sakura_core/apiwrap/StdApi.h
  sakura_core/apiwrap/StdControl.h
  sakura_core/basis/CMyString.h
  sakura_core/basis/primitive.h
  sakura_core/charset/CharPointer.h
  sakura_core/charset/charcode.h
  sakura_core/cmd/CViewCommander_Edit.cpp
  sakura_core/config/build_config.h
  sakura_core/config/system_constants.h
  sakura_core/debug/Debug1.cpp
  sakura_core/debug/Debug1.h
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgPluginOption.cpp
  sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
  sakura_core/extmodule/CMigemo.h
  sakura_core/macro/CIfObj.cpp
  sakura_core/mem/CNativeA.h
  sakura_core/mem/CNativeT.h
  sakura_core/mem/CNativeW.h
  sakura_core/outline/CFuncInfoArr.cpp
  sakura_core/plugin/CPlugin.cpp
  sakura_core/plugin/CPluginManager.cpp
  sakura_core/print/CPrintPreview.cpp
  sakura_core/prop/CPropComMainMenu.cpp
  sakura_core/uiparts/CImageListMgr.cpp
  sakura_core/util/file.cpp
  sakura_core/util/file.h
  sakura_core/util/format.cpp
  sakura_core/util/shell.cpp
  sakura_core/util/string_ex.cpp
  sakura_core/util/string_ex.h
  sakura_core/util/string_ex2.h
  sakura_core/util/tchar_convert.h
  sakura_core/util/tchar_printf.cpp
  sakura_core/util/tchar_receive.cpp
  sakura_core/version.h
  sakura_core/view/CEditView.cpp
  sakura_core/view/CEditView_Mouse.cpp
  sakura_core/view/CRuler.cpp
  sakura_core/view/CTextDrawer.cpp
  sakura_core/view/figures/CFigureStrategy.cpp
  sakura_core/view/figures/CFigure_Comma.cpp
  sakura_core/view/figures/CFigure_CtrlCode.cpp
  sakura_core/view/figures/CFigure_Eol.cpp
  sakura_core/view/figures/CFigure_HanSpace.cpp
  sakura_core/view/figures/CFigure_Tab.cpp
  sakura_core/view/figures/CFigure_ZenSpace.cpp
  sakura_core/window/CSplitBoxWnd.cpp
Labels: refactoring

#1011 シンボリックリンク自体のタイムスタンプではなくターゲットのタイムスタンプを取得するように修正
  sakura_core/util/file.cpp
Labels: 🐛bug🦋

#1012 SDLチェックを有効にする(Take2)
  sakura/sakura.vcxproj
Labels: refactoring

#1015 CEditView::CreateOrUpdateCompatibleBitmap において画面バッファを作成する条件を変更
  sakura_core/view/CEditView_Paint.cpp
Labels: speed up

#1016 関数ポインタの代入式を簡潔にする
  sakura_core/CKeyWordSetMgr.cpp
  sakura_core/view/CEditView_Search.cpp
Labels: refactoring

#1017 ShiftJISの文字を数えるのに使う型を訂正
  sakura_core/view/CEditView_ExecCmd.cpp
Labels: refactoring

#1018 Visual Studio 2017以降のみのサポートなので、冗長なプリプロセッサ判定や使用されないコードを削る
  sakura_core/StdAfx.h
  sakura_core/apiwrap/StdApi.h
  sakura_core/basis/CStrictInteger.cpp
  sakura_core/charset/CESI.cpp
  sakura_core/config/build_config.cpp
  sakura_core/config/build_config.h
  sakura_core/debug/Debug1.h
  sakura_core/dlg/CDlgProperty.cpp
  sakura_core/extmodule/CUxTheme.h
  sakura_core/plugin/CPluginManager.cpp
  sakura_core/prop/CPropComBackup.cpp
  sakura_core/util/string_ex.cpp
  sakura_core/util/string_ex.h
Labels: refactoring

#1019 未使用の ANSI 系独自関数を削る
  sakura_core/mem/CNativeA.cpp
  sakura_core/mem/CNativeA.h
  sakura_core/util/file.cpp
  sakura_core/util/file.h
  sakura_core/util/string_ex2.cpp
  sakura_core/util/string_ex2.h
Labels: refactoring
