Repository sakura-editor/sakura, pull requests merged in 2019-03, with the labels that each got.

#808 PR 421 によって導入されたけど revert された IsMailAddress の単体テストを復活する
  tests/unittests/test-is_mailaddress.cpp
Labels: UnitTest

#815 成果物の ZIP 内部のフォルダを短くする (「リリースファイルのファイル名が長すぎるのでは?」 に対応する)
  zipArtifacts.bat
Labels: CI

#812 「同名のC/C++ヘッダ(ソース)を開く」機能が利用可能か調べる処理で拡張子の確認が行われるように記述追加
  sakura_core/cmd/CViewCommander_File.cpp
  sakura_core/func/Funccode.cpp
Labels: enhancement

#822 IsMailAddress の仮引数名修正
  sakura_core/parse/CWordParse.cpp
  sakura_core/parse/CWordParse.h
  tests/unittests/test-is_mailaddress.cpp
Labels: refactoring

#818 skip_commits を追加して、appveyor のビルドで無視するファイルを追加する
  appveyor.yml
Labels: CI

#813 CHANGELOG.md を追加する
  CHANGELOG.md
Labels: Release, management

#819 azure-pipelines のファイルを追加
  azure-pipelines-template.yml
  azure-pipelines.md
  azure-pipelines.yml
Labels: CI

#820 appveyor で Debug/Release の順番を逆にする
  appveyor.yml
Labels: CI
