Repository sakura-editor/sakura, pull requests merged in 2019-01, with the labels that each got.

#726 ウィンドウ一覧画面を開いた後にウィンドウサイズを大きくしてから閉じて開き直すとウィンドウサイズにコントロールが追従していない問題を修正
  sakura_core/dlg/CDlgWindowList.cpp
Labels: bug

#747 pip install を install セクションに移動する
  appveyor.yml
  checkEncoding.bat
  parse-buildlog.bat
Labels: refactoring

#750 grep で 除外ファイル、除外フォルダが効かない問題を修正するため、除外パターンを指定するコマンドラインを復活する
  help/sakura/_RESOURCE/HLP000109.html
  sakura_core/_main/CCommandLine.cpp
  sakura_core/_main/CControlTray.cpp
Labels: bug

#751 appveyor.yml のコマンド実行処理をリファクタリング
  appveyor.yml
Labels: refactoring

#716 Common File Dialog の代わりに Common Item Dialog を使用する
  .gitattributes
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/Makefile
  sakura_core/String_define.h
  sakura_core/config/system_constants.h
  sakura_core/dlg/CDlgOpenFile.cpp
  sakura_core/dlg/CDlgOpenFile.h
  sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp
  sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/env/CShareData_IO.cpp
  sakura_core/env/CommonSetting.h
  sakura_core/prop/CPropComEdit.cpp
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#764 WinMain のコメントを修正する
  sakura_core/_main/WinMain.cpp
Labels: document

#653 ビルドツールの検索を改善
  build-chm.bat
  build-installer.bat
  build-sln.bat
  run-cppcheck.bat
  run-doxygen.bat
  tools/CppCheck/find-CppCheck.bat
  tools/CppCheck/readme.md
  tools/ISCC/find-ISCC.bat
  tools/ISCC/readme.md
  tools/doxygen/find-doxygen.bat
  tools/doxygen/readme.md
  tools/find-tools.bat
  tools/find-tools.md
  tools/hhc/find-hhc.bat
  tools/hhc/readme.md
  tools/msbuild/find-msbuild.bat
  tools/msbuild/readme.md
  tools/zip/find-7z.bat
  tools/zip/listzip.bat
  tools/zip/unzip.bat
  tools/zip/zip.bat
Labels: CI
