Repository sakura-editor/sakura, pull requests merged in 2019-04, with the labels that each got.

#829 EXEとInstallerのzipのmd5ファイルを作成
  appveyor.yml
  zipArtifacts.bat
Labels: CI

#826 azure pipelines でインストーラのビルドを行う
  appveyor.yml
  azure-pipelines-template.yml
  azure-pipelines.yml
  ci/azure-pipelines/template-build-unittest.yml
  ci/azure-pipelines/template-checkEncoding.yml
  ci/azure-pipelines/template-cppcheck.yml
  ci/azure-pipelines/template-doxygen.yml
Labels: CI, azure pipelines

#831 doxygen 関連の生成ファイルを git から除外する
  .gitignore
Labels: doxygen

#828 appveyor のドキュメント内の環境変数部分を修正
  appveyor.md
Labels: CI, document

#825 azure pipelines の badge を追加
  README.md
Labels: CI, document

#833 azure pipelines で代用可能な処理を appveyor で実施しないようにする
  appveyor.yml
  build-all.bat
Labels: CI, appveyor, azure pipelines

#839 `azure pipelinesメモ` へのリンクを追加
  azure-pipelines.md
Labels: azure pipelines, document

#832 Visual Studio 2019 インストール環境でのビルドエラー修正
  tools/find-tools.bat
Labels: CI, appveyor, azure pipelines, bug, visual studio 2019

#843 azure pipelines の template のファイル名を名前変更
  azure-pipelines.yml
  ci/azure-pipelines/template.steps.build-unittest.yml
  ci/azure-pipelines/template.steps.checkEncoding.yml
  ci/azure-pipelines/template.steps.cppcheck.yml
  ci/azure-pipelines/template.steps.doxygen.yml
Labels: CI, azure pipelines

#846 コンパイラを区別するマクロに関してコメントを追加
  sakura_core/dlg/CDlgAbout.cpp
Labels: no-changelog

#845 Vistaスタイルのファイルダイアログでカスタマイズ部分が表示されない場合がある問題の修正
  sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp
Labels: bug

#852 PR #846 で入れたコメントのうち Intel Compiler のドキュメントに対するリンクを修正
  sakura_core/dlg/CDlgAbout.cpp
Labels: document, no-changelog

#853 1文字の比較で wcsncmp 関数を使うのは止める
  sakura_core/view/CEditView_Paint_Bracket.cpp
Labels: speed up

#850 Parameterized Test のサンプルを追加
  tests/unittests/test-parameterized.cpp
Labels: UnitTest, no-changelog

#859 STR_IMPEXP_VER の書式フォーマット指定を見直す
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: refactoring

#851 azure pipelines のドキュメントおよびコメントを追加
  README.md
  azure-pipelines.md
  azure-pipelines.yml
  build.md
Labels: CI, azure pipelines, document

#861 readme.md でドキュメントの項目の分類の誤りを修正
  README.md
Labels: document

#865 Azure Pipelines で JOB のテンプレートを使う
  azure-pipelines.md
  azure-pipelines.yml
  ci/azure-pipelines/template.job.build-unittest.yml
  ci/azure-pipelines/template.job.checkEncoding.yml
  ci/azure-pipelines/template.job.cppcheck.yml
  ci/azure-pipelines/template.job.doxygen.yml
  ci/azure-pipelines/template.steps.build-unittest.yml
  ci/azure-pipelines/template.steps.checkEncoding.yml
  ci/azure-pipelines/template.steps.cppcheck.yml
  ci/azure-pipelines/template.steps.doxygen.yml
Labels: CI, azure pipelines, refactoring

#854 不要な CCaret::ShowCaretPosInfo の呼び出しを無くす
  sakura_core/cmd/CViewCommander_Cursor.cpp
Labels: speed up

#836 タグジャンプにてタグ検索が二分探索可能な場合は二分探索を行うようにした
  sakura_core/dlg/CDlgTagJumpList.cpp
  sakura_core/dlg/CDlgTagJumpList.h
  sakura_core/env/CShareData.cpp
  sakura_core/env/CShareData_IO.cpp
  sakura_core/env/CTagJumpManager.h
Labels: speed up

#848 Azure Pipelines ですべての python スクリプトのコンパイル確認を行う
  azure-pipelines.md
  azure-pipelines.yml
  ci/azure-pipelines/template.job.build-unittest.yml
  ci/azure-pipelines/template.job.python-check.yml
  ci/azure-pipelines/template.steps.install-python-modules.yml
Labels: CI, azure pipelines

#866 PlatformToolset 指定をプロパティーシートに分離して VS2017 および VS2019 で両対応できるようにする
  HeaderMake/HeaderMake.vcxproj
  MakefileMake/MakefileMake.vcxproj
  README.md
  sakura/sakura.vcxproj
  sakura_lang_en_US/sakura_lang_en_US.vcxproj
  vcx-props/project-PlatformToolset.md
  vcx-props/vcxcompat.props
Labels: enhancement

#870 README.md の #866 の PR に対するリンクを修正
  README.md
Labels: document

#869 azure pipelines => Azure Pipelines に変更
  azure-pipelines.md
  build.md
Labels: document

#674 SonarQube (SonarCloud) 対応
  .gitignore
  README.md
  SonarQube.md
  appveyor-SonarQube.png
  azure-SonarQube-schedule1.png
  azure-SonarQube-schedule2.png
  azure-SonarQube-schedule3.png
  azure-SonarQube.png
  azure-pipelines.md
  azure-pipelines.yml
  build-sln.bat
  build-sonar-qube-env.bat
  build-sonar-qube-finish.bat
  build-sonar-qube-start.bat
  ci/azure-pipelines/template.job.SonarQube.yml
  ci/azure-pipelines/template.job.checkEncoding.yml
Labels: CI, azure pipelines, research, static analysis

#879 SonarQube 用の JOB 以外で SonarQube の解析が走らないようにする
  build-sonar-qube-env.bat
Labels: CI, IMPORTANT, azure pipelines, bug

#874 Vistaスタイルのファイルダイアログ使用時に名前を付けて保存の文字コードセット, 改行コード, BOM指定が有効に動作しない問題を修正
  sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp
Labels: bug

#867 Vistaスタイルのファイルダイアログ使用時に新規ファイルの保存が行えない問題を修正
  sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp
Labels: bug

#883 SonarQube で `/d:sonar.cfamily.threads` を指定して SonarQube を高速化する
  build-sonar-qube-start.bat
Labels: CI, SonarQube, azure pipelines, speed up, static analysis

#887 SonarQubeのMarkDown用画像ファイルをci配下に移す
  SonarQube.md
  ci/appveyor/appveyor-SonarQube.png
  ci/azure-pipelines/azure-SonarQube-schedule1.png
  ci/azure-pipelines/azure-SonarQube-schedule2.png
  ci/azure-pipelines/azure-SonarQube-schedule3.png
  ci/azure-pipelines/azure-SonarQube.png
Labels: document, no-changelog
