Repository sakura-editor/sakura, pull requests merged in 2019-10, with the labels that each got.

#1065 ノート線描画、指定桁縦線描画、折り返し桁縦線描画、を行毎ではなく一括で行うように変更
  sakura_core/view/CEditView.h
  sakura_core/view/CEditView_Paint.cpp
Labels: :bullettrain_front: speed up :rocket:

#1067 ルーラー描画の高速化
  sakura_core/view/CRuler.cpp
  sakura_core/view/CRuler.h
Labels: :bullettrain_front: speed up :rocket:

#1070 プログラム内からドキュメントにアクセスする方法を分かりやすくする
  sakura_core/_os/CClipboard.cpp
  sakura_core/dlg/CDlgExec.cpp
  sakura_core/doc/CDocListener.cpp
  sakura_core/doc/CDocVisitor.cpp
  sakura_core/doc/CEditDoc.cpp
  sakura_core/doc/CEditDoc.h
  sakura_core/env/CSakuraEnvironment.cpp
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/util/design_template.h
  sakura_core/view/CTextDrawer.cpp
  sakura_core/view/DispPos.cpp
  sakura_core/view/DispPos.h
  sakura_core/view/colors/CColorStrategy.cpp
  sakura_core/view/colors/CColorStrategy.h
  sakura_core/view/colors/CColor_Comment.h
  sakura_core/view/colors/CColor_Quote.cpp
  sakura_core/view/figures/CFigureStrategy.h
Labels: refactoring

#1072 行毎ではなく一括で線を描く変更によって引き起こされた表示の不具合を起こさないように元に戻す
  sakura_core/view/CEditView.h
  sakura_core/view/CEditView_Paint.cpp
  sakura_core/view/CEditView_Paint_Bracket.cpp
  sakura_core/view/CTextDrawer.cpp
  sakura_core/view/CTextDrawer.h
Labels: degradation, 🐛bug🦋

#1074 プログラム内からドキュメントにアクセスする方法を分かりやすくする変更を revert
  sakura_core/_os/CClipboard.cpp
  sakura_core/dlg/CDlgExec.cpp
  sakura_core/doc/CDocListener.cpp
  sakura_core/doc/CDocVisitor.cpp
  sakura_core/doc/CEditDoc.cpp
  sakura_core/doc/CEditDoc.h
  sakura_core/env/CSakuraEnvironment.cpp
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/util/design_template.h
  sakura_core/view/CTextDrawer.cpp
  sakura_core/view/DispPos.cpp
  sakura_core/view/DispPos.h
  sakura_core/view/colors/CColorStrategy.cpp
  sakura_core/view/colors/CColorStrategy.h
  sakura_core/view/colors/CColor_Comment.h
  sakura_core/view/colors/CColor_Quote.cpp
  sakura_core/view/figures/CFigureStrategy.h
Labels: 🐛bug🦋

#1075 Release/v2.4.0 beta prepare
  help/sakura/res/HLP000001.html
  sakura/githash.bat
Labels: Release
