Repository sakura-editor/sakura, pull requests merged in 2019-09, with the labels that each got.

#1021 フォントサイズ変更時に不要な処理の呼び出しを行わないように判定追加
  sakura_core/cmd/CViewCommander_Settings.cpp
  sakura_core/doc/CEditDoc.cpp
  sakura_core/doc/CEditDoc.h
Labels: speed up

#1047 zip版でもgithash.hが作られるようにする
  sakura/githash.targets
Labels: no-changelog

#1042 文字列比較関数の第2引数に文字列リテラルを渡す場合は大きさを自動取得するテンプレート関数を使うように変更
  sakura_core/CRegexKeyword.cpp
  sakura_core/convert/convert_util2.h
  sakura_core/doc/CDocOutline.cpp
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/typeprop/CDlgTypeList.cpp
  sakura_core/types/CType_Cpp.cpp
  sakura_core/types/CType_Erlang.cpp
  sakura_core/util/format.cpp
  sakura_core/util/string_ex.h
  sakura_core/util/tchar_printf.cpp
  sakura_core/view/CEditView_Diff.cpp
  sakura_core/view/CEditView_Mouse.cpp
Labels: refactoring

#1052 レイアウト処理の負荷を下げる為、コメントが色分け表示対象外になる機会を増やす
  sakura_core/doc/CLineComment.h
  sakura_core/view/colors/CColor_Comment.h
Labels: :bullettrain_front: speed up :rocket:

#1053 VC++の規格準拠モードをONにする
  sakura/sakura.vcxproj
  sakura_core/types/CType_Cpp.cpp
  sakura_core/view/CTextDrawer.cpp
Labels: refactoring

#1054 ファイル保存の副次処理調整
  sakura_core/CSaveAgent.cpp
  sakura_core/CWriteManager.cpp
Labels: :bullettrain_front: speed up :rocket:

#1056 レイアウト情報の作成処理をわずかに高速化
  sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
Labels: :bullettrain_front: speed up :rocket:

#1058 CMemory(CNativeW/CNativeA)をムーブ可能にする
  sakura_core/mem/CMemory.cpp
  sakura_core/mem/CMemory.h
  sakura_core/mem/CNativeA.cpp
  sakura_core/mem/CNativeA.h
  sakura_core/mem/CNativeW.cpp
  sakura_core/mem/CNativeW.h
Labels: refactoring

#1059 文字コードの指定ダイアログのCPチェックの仕様を修正する
  sakura_core/dlg/CDlgSetCharSet.cpp
  sakura_core/dlg/CDlgSetCharSet.h
Labels: 🐛bug🦋

#1061 確保済みメモリサイズの更新タイミングを訂正する
  sakura_core/mem/CMemory.cpp
Labels: 🐛bug🦋

#1062 std::wstring を使った記述の微調整
  sakura_core/CGrepAgent.cpp
  sakura_core/CHokanMgr.cpp
  sakura_core/charset/charset.cpp
  sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/plugin/CComplementIfObj.h
  sakura_core/plugin/CPluginManager.cpp
  sakura_core/typeprop/CImpExpManager.cpp
  sakura_core/typeprop/CPropTypesSupport.cpp
  sakura_core/util/string_ex2.h
  sakura_core/view/CEditView_CmdHokan.cpp
  sakura_core/window/CEditWnd.cpp
Labels: refactoring

#1063 最近使ったファイル挿入 と 最近使ったフォルダ挿入 を行う機能追加
  resource/MainMenu.ini
  resource/mytool.bmp
  sakura_core/Funccode_x.hsrc
  sakura_core/cmd/CViewCommander.cpp
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_Insert.cpp
  sakura_core/doc/CEditDoc.cpp
  sakura_core/func/Funccode.cpp
  sakura_core/macro/CSMacroMgr.cpp
  sakura_core/sakura_rc.rc
  sakura_core/uiparts/CMenuDrawer.cpp
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#1064 x64対応をスムーズに行うために、文字列長取得メソッドのオーバーロードを廃止する
  sakura_core/CGrepAgent.cpp
  sakura_core/CSearchAgent.cpp
  sakura_core/charset/CCodePage.cpp
  sakura_core/charset/CEuc.cpp
  sakura_core/charset/CJis.cpp
  sakura_core/charset/CLatin1.cpp
  sakura_core/charset/CShiftJis.cpp
  sakura_core/charset/CUnicode.cpp
  sakura_core/charset/CUtf7.cpp
  sakura_core/charset/CUtf8.cpp
  sakura_core/cmd/CViewCommander_Clipboard.cpp
  sakura_core/cmd/CViewCommander_Convert.cpp
  sakura_core/cmd/CViewCommander_Edit_advanced.cpp
  sakura_core/cmd/CViewCommander_Search.cpp
  sakura_core/mem/CMemory.cpp
  sakura_core/mem/CMemory.h
  sakura_core/mem/CNativeA.cpp
  sakura_core/mem/CNativeA.h
  sakura_core/mem/CNativeW.cpp
  sakura_core/mem/CNativeW.h
  sakura_core/view/CEditView_Diff.cpp
Labels: refactoring
