Repository sakura-editor/sakura, pull requests merged in 2020-10, with the labels that each got.

#1419 未使用のCFigureクラス(全角バイナリと半角バイナリ)を除去する
  sakura_core/view/figures/CFigureManager.cpp
  sakura_core/view/figures/CFigure_CtrlCode.cpp
  sakura_core/view/figures/CFigure_CtrlCode.h
Labels: refactoring

#1422 XML宣言を用いた文字コード判別処理を強化する
  sakura_core/charset/CESI.cpp
Labels: 🐛bug🦋

#1421 ダイアログフォント美化
  sakura_core/dlg/CDialog.cpp
  sakura_core/dlg/CDialog.h
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/dlg/CDlgGrep.cpp
  sakura_core/dlg/CDlgGrepReplace.cpp
  sakura_core/dlg/CDlgInput1.cpp
  sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp
  sakura_core/dlg/CDlgPrintSetting.cpp
  sakura_core/dlg/CDlgPrintSetting.h
  sakura_core/dlg/CDlgReplace.cpp
  sakura_core/print/CPrintPreview.cpp
  sakura_core/prop/CPropCommon.cpp
  sakura_core/sakura_rc.rc
  sakura_core/typeprop/CPropTypes.cpp
  sakura_core/util/window.cpp
  sakura_core/util/window.h
Labels: enhancement

#1427 引数の文字列コピーに検出したnArgLenを使う
  sakura_core/_main/CCommandLine.cpp
Labels: refactoring

#1425 プロパティシートに対してシステムフォントを設定
  sakura_core/util/shell.cpp
  sakura_core/util/window.cpp
  sakura_core/util/window.h
Labels: specification change

#1429 コマンドライン解析で解析した「タイプ」を内部変数にコピーする際の文字列コピーの記述が冗長なのを修正する
  sakura_core/_main/CCommandLine.cpp
  tests/unittests/test-ccommandline.cpp
Labels: refactoring

#1430 CFigure_Comma::Matchの実装内容を他のCFigureと合わせる
  sakura_core/view/figures/CFigure_Comma.cpp
  sakura_core/view/figures/CFigure_Comma.h
Labels: refactoring

#1432 利用できないコマンドラインオプション「-WQ(INIファイルを出力して即終了)」を削除する
  help/sakura/res/HLP000109.html
  sakura_core/_main/CCommandLine.cpp
  sakura_core/_main/CCommandLine.h
  sakura_core/_main/CControlProcess.cpp
  sakura_core/_main/CProcessFactory.cpp
  sakura_core/_main/CProcessFactory.h
  sakura_core/env/CFileNameManager.cpp
  tests/unittests/test-ccommandline.cpp
Labels: document, refactoring

#1428 XML文書にタイプ別設定で選択した文字コードを使えるようにする
  sakura_core/charset/CESI.cpp
Labels: specification change

#1436 googletestとcompiletestsを2回目のビルドに対応させる
  tests/compiletests.run.cmd
  tests/compiletests.targets
  tests/googletest.build.cmd
  tests/googletest.targets
Labels: local build

#1440 デバッグ実行時に外部コマンド実行ダイアログを開くとwarning_point関数で止まる問題を修正する
  sakura_core/dlg/CDlgExec.cpp
Labels: 🐛bug🦋

#1431 Grepダイアログ部品配置の改善
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#1448 Grep置換ダイアログに誤追加された「否該当行」を削除
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: 🐛bug🦋
