Repository sakura-editor/sakura, pull requests merged in 2020-05, with the labels that each got.

#1259 sakura editor のビルド用の GitHub Actions を導入する
  .github/workflows/build-sakura.yml
  appveyor.yml
  azure-pipelines.yml
Labels: CI

#1264 CDialog::OnNotify の引数の型を変更して、不要なキャストをなくす
  sakura_core/dlg/CDialog.cpp
  sakura_core/dlg/CDialog.h
  sakura_core/dlg/CDlgCtrlCode.cpp
  sakura_core/dlg/CDlgCtrlCode.h
  sakura_core/dlg/CDlgFavorite.cpp
  sakura_core/dlg/CDlgFavorite.h
  sakura_core/dlg/CDlgJump.cpp
  sakura_core/dlg/CDlgJump.h
  sakura_core/dlg/CDlgPluginOption.cpp
  sakura_core/dlg/CDlgPluginOption.h
  sakura_core/dlg/CDlgPrintSetting.cpp
  sakura_core/dlg/CDlgPrintSetting.h
  sakura_core/dlg/CDlgTagJumpList.cpp
  sakura_core/dlg/CDlgTagJumpList.h
  sakura_core/outline/CDlgFileTree.cpp
  sakura_core/outline/CDlgFileTree.h
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/outline/CDlgFuncList.h
Labels: refactoring

#1277 PRテンプレートに仕様・動作説明欄を追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog

#1278 GitHub Actions の状態を Badge を追加
  README.md
Labels: document, no-changelog

#1274 テスト内容 を Pull Request Template に追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog

#1291 Combo_AddString の戻り値の型を int にする
  sakura_core/apiwrap/StdControl.h
Labels: x64

#1293 installer のタイトルのアプリ名で 32bit/64bit の区別ができるようにする
  installer/sakura-common.iss
Labels: installer

#1294 Pull Request Template に入れた(必須)とか(省略可)をコメント化
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog

#1282 v2.4.1 beta2 リリース準備
  help/sakura/res/HLP000001.html
  sakura/githash.bat
Labels: Release

#1300 v2.4.0 リリースに伴うCHANGELOG.md反映
  CHANGELOG.md
Labels: Release

#1309 README.md の「変更履歴」に CHANGELOG.md へのリンクを追加
  README.md
Labels: document

#1310 v2.4.1-Beta3 release.
  help/sakura/res/HLP000001.html
  sakura/githash.bat
Labels: Release

#1312 v2.4.1 beta3 までの CHANGELOG.md を反映
  CHANGELOG.md
Labels: Release

#1271 Azure Pipelines/GitHub Actions で HTML Help をビルドできるようにする
  .github/workflows/build-sakura.yml
  build-chm.bat
  ci/azure-pipelines/template.job.build-unittest.yml
  tools/find-tools.bat
  tools/find-tools.md
Labels: CI

#1314 ツールバーの折り返しが機能しないデグレの修正を revert
  sakura_core/apiwrap/CommonControl.h
  sakura_core/window/CMainToolBar.cpp
Labels: 🐛bug🦋, 💩degradation🧻🚽
