Repository sakura-editor/sakura, pull requests merged in 2020-11, with the labels that each got.

#1455 #1449を訂正してADSを使えるにする
  sakura_core/util/file.cpp
  tests/unittests/test-ccommandline.cpp
  tests/unittests/test-file.cpp
Labels: 💩degradation🧻🚽

#1457 [要望]ツールバー編集画面においてボタン挿入・追加時に機能リストのフォーカスを1つ下にずらしてほしい
  sakura_core/prop/CPropComToolbar.cpp
Labels: specification change

#1459 （#1457 補遺）カスタムメニュー画面でも追加・挿入後に機能リストを送る処理を入れたい
  sakura_core/prop/CPropComCustmenu.cpp
Labels: specification change

#1461 Combo_GetEditSel 関数の変更
  sakura_core/apiwrap/StdControl.h
  sakura_core/dlg/CDialog.cpp
Labels: refactoring, 🐛bug🦋

#1465 MinGWのプリコンパイル済みヘッダーを.gitignoreに追加する
  sakura_core/.gitignore
Labels: Git, MinGW

#1453 サクラエディタのコマンドライン引数に超長い文字列を指定するとクラッシュする問題に対処する。(Take2)
  sakura_core/_main/CCommandLine.cpp
  tests/unittests/test-ccommandline.cpp
Labels: 🐛bug🦋

#1463 コンボボックスのサブクラス化処理を簡素化する
  sakura_core/dlg/CDialog.cpp
  sakura_core/dlg/CDialog.h
  sakura_core/dlg/CDlgExec.cpp
  sakura_core/dlg/CDlgExec.h
  sakura_core/dlg/CDlgFind.cpp
  sakura_core/dlg/CDlgFind.h
  sakura_core/dlg/CDlgGrep.cpp
  sakura_core/dlg/CDlgGrep.h
  sakura_core/dlg/CDlgGrepReplace.cpp
  sakura_core/dlg/CDlgGrepReplace.h
  sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp
  sakura_core/dlg/CDlgReplace.cpp
  sakura_core/dlg/CDlgReplace.h
  sakura_core/dlg/CDlgTagJumpList.cpp
  sakura_core/dlg/CDlgTagJumpList.h
  sakura_core/window/CMainToolBar.cpp
  sakura_core/window/CMainToolBar.h
Labels: refactoring

#1456 リソースエディタで編集不可のものを.rc2に分離
  .gitattributes
  checkEncoding.py
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/.gitignore
  sakura_core/Makefile
  sakura_core/sakura_rc.h
  sakura_core/sakura_rc.rc
  sakura_core/sakura_rc.rc2
  sakura_lang_en_US/sakura_lang_en_US.vcxproj
  sakura_lang_en_US/sakura_lang_en_US.vcxproj.filters
  sakura_lang_en_US/sakura_lang_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc2
Labels: refactoring

#1470 コンボボックスに Ctrl+Backspace による単語削除機能を追加する
  sakura_core/CSearchAgent.cpp
  sakura_core/dlg/CDialog.cpp
  sakura_core/parse/CWordParse.cpp
  sakura_core/parse/CWordParse.h
Labels: enhancement

#1471 PRテンプレートの「影響範囲」を「テスト内容」の前にする
  .github/PULL_REQUEST_TEMPLATE.md
Labels: management
