Repository sakura-editor/sakura, pull requests merged in 2020-02, with the labels that each got.

#1153 Beta3までのチェンジログ反映。
  CHANGELOG.md
Labels: document, no-changelog

#1176 C++ファイルのアウトライン解析がトグルで閉じない不具合の修正
  sakura_core/cmd/CViewCommander_Outline.cpp
  sakura_core/types/CType.h
  sakura_core/types/CType_Cpp.cpp
Labels: 🐛bug🦋

#1184 githash.bat の処理をリファクタリングする
  sakura/githash.bat
Labels: refactoring

#1183 Appveyor 専用の環境変数を汎用的なものに定義しなおして azure pipelines で使えるようにする
  README.md
  appveyor.md
  azure-pipelines.md
  ci-build.md
  help/make-artifacts.bat
  sakura/githash.bat
  zipArtifacts.bat
Labels: CI, appveyor, azure pipelines

#1193 TEMP_GIT_SHORT_COMMIT_HASH および TEMP_GIT_COMMIT_HASH を廃止する
  ci-build.md
  help/make-artifacts.bat
  sakura/githash.bat
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
  zipArtifacts.bat
Labels: CI, appveyor, azure pipelines, local build

#1197 Release/v2.4.0 beta4
  help/sakura/res/HLP000001.html
  sakura/githash.bat
Labels: Release

#1199 C#ツールの.vsconfigを追加する
  tools/ChmSourceConverter/.vsconfig
  tools/ToolBarTools/.vsconfig
Labels: local build

#1200 GITHUB_COMMIT_URL_PR_HEAD から GITHUB_PR_HEAD_URL に改名
  appveyor_env.py
  ci-build.md
  sakura/githash.bat
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: CI, appveyor, azure pipelines, refactoring

#1202 ヘルプのコピーライトの年とソフト名変更。
  help/sakura/res/HLP000001.html
Labels: document
