Repository sakura-editor/sakura, pull requests merged in 2020-09, with the labels that each got.

#1387 MSVCビルドでMinGWビルド向けのMakefileが更新されるとMakefileが壊れるのでMakefile更新をやめたい
  MakefileMake/.gitignore
  MakefileMake/MakefileMake.cpp
  MakefileMake/MakefileMake.vcxproj
  sakura.sln
  sakura/gen-makefile.bat
  sakura/mingw32-del.bat
  sakura/preBuild.bat
  sakura/sakura.vcxproj
Labels: environment

#1389 言語DLLのMakefileのMYDEFINESの指定方法をシンプルに戻す
  sakura_lang_en_US/Makefile
Labels: MinGW, environment

#1390 MYDEFINESに-DNDEBUGが指定されてない対策の改良
  sakura_core/Makefile
  sakura_lang_en_US/Makefile
Labels: MinGW, environment

#1320 PageUp, PageDown 時に描画する必要が無い場合は描画しないようにする判定を追加
  sakura_core/cmd/CViewCommander_Cursor.cpp
Labels: :bullettrain_front: speed up :rocket:

#1393 画面先頭行を取得するマクロ関数 GetViewTop を追加
  help/sakura/res/HLP000268.html
  sakura_core/Funccode_x.hsrc
  sakura_core/macro/CMacro.cpp
  sakura_core/macro/CSMacroMgr.cpp
Labels: enhancement

#1396 CImageListMgr::Create において読み込んだビットマップの形式を 32bit に変換する処理を追加
  sakura_core/uiparts/CImageListMgr.cpp
Labels: specification change, 🐛bug🦋

#1401 aps ファイルを無視する
  .gitignore
Labels: environment

#1403 CI の成果物をアップするのを Release 版に限定する
  .github/workflows/build-sakura.yml
  appveyor.yml
  ci/azure-pipelines/template.job.build-unittest.yml
Labels: CI

#1400 GREPダイアログ内の全コンボボックスに対してフォント設定で指定されたフォントを使用する
  sakura_core/dlg/CDlgGrep.cpp
  sakura_core/dlg/CDlgGrep.h
Labels: specification change

#1398 アウトライン解析の選択行追従
  sakura_core/doc/CDocEditor.cpp
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/outline/CDlgFuncList.h
  sakura_core/view/CCaret.cpp
Labels: enhancement

#1399 キーワードヘルプの説明文に"\n"を表示できるようにしたい。
  help/sakura/res/HLP000105.html
  sakura_core/cmd/CViewCommander_CustMenu.cpp
  sakura_core/view/CEditView.cpp
  sakura_core/view/CEditView_Search.cpp
  sakura_core/window/CTipWnd.cpp
  sakura_core/window/CTipWnd.h
Labels: specification change

#1384 TrySelectProfileテストを改善する
  tests/unittests/test-cdlgprofilemgr.cpp
Labels: Test, UnitTest, no-changelog, 🐛bug🦋

#1385 サクラエディタの起動テストを追加する
  sakura_core/_main/CProcessFactory.cpp
  tests/unittests/StartEditorProcessForTest.h
  tests/unittests/code-main.cpp
  tests/unittests/test-winmain.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: Test

#1405 一度にExtTextOutで描画しての高速化
  sakura_core/view/CEditView_Paint.cpp
  sakura_core/view/CTextMetrics.cpp
  sakura_core/view/figures/CFigureStrategy.cpp
  sakura_core/view/figures/CFigureStrategy.h
Labels: :bullettrain_front: speed up :rocket:

#1414 ファイル内容比較ダイアログの未使用処理pszCompareLabelを削除
  sakura_core/cmd/CViewCommander_Diff.cpp
  sakura_core/dlg/CDlgCompare.cpp
  sakura_core/dlg/CDlgCompare.h
Labels: refactoring

#1413 DIFF差分とウィンドウ一覧ダイアログでファイル名がMAX_PATHぎりぎりだと落ちてしまう不具合の修正
  sakura_core/dlg/CDlgDiff.cpp
  sakura_core/dlg/CDlgWindowList.cpp
Labels: 🐛bug🦋

#1411 CGraphics 関連の最適化
  sakura_core/view/CEditView.h
  sakura_core/view/CEditView_Paint.cpp
  sakura_core/view/CEditView_Paint_Bracket.cpp
  sakura_core/view/colors/CColorStrategy.h
  sakura_core/view/figures/CFigure_Eol.cpp
  sakura_core/view/figures/CFigure_Eol.h
Labels: :bullettrain_front: speed up :rocket:

#1415 テキスト幅計算に使用する文字間隔配列のコンテナを使いまわす事で負荷を削減
  sakura_core/print/CPrintPreview.cpp
  sakura_core/view/CTextMetrics.cpp
  sakura_core/view/CTextMetrics.h
Labels: :bullettrain_front: speed up :rocket:
