Repository sakura-editor/sakura, pull requests merged in 2020-08, with the labels that each got.

#1358 空行描画のオプションが誤っているのを修正する。
  sakura_core/window/CTipWnd.cpp
Labels: 🐛bug🦋

#1375 MinGWビルドシステムの改善
  HeaderMake/.gitignore
  build-gnu.bat
  build.md
  sakura_core/.gitignore
  sakura_core/Makefile
Labels: MinGW, no-changelog

#1372 MinGW: C++ の未定義動作によるクラッシュを修正する
  sakura_core/cmd/CViewCommander_TagJump.cpp
  sakura_core/doc/layout/CLayout.h
  sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
  sakura_core/doc/logic/CDocLine.h
  sakura_core/env/CAppNodeManager.h
  sakura_core/mfclike/CMyWnd.h
  sakura_core/print/CPrintPreview.h
  sakura_core/view/CEditView.cpp
  sakura_core/view/CEditView_Paint.cpp
  sakura_core/view/colors/CColorStrategy.cpp
  sakura_core/view/colors/CColorStrategy.h
  sakura_core/window/CEditWnd.cpp
Labels: MinGW

#1376 英語リソースに英語の言語IDを使う
  sakura_lang_en_US/sakura_lang_en_US.vcxproj
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: Internationalization

#1379 MinGW: プリコンパイルヘッダの依存関係の修正
  sakura_core/Makefile
Labels: MinGW, environment

#1382 MinGW: Fix SEGV
  sakura_core/view/CEditView_Paint_Bracket.cpp
Labels: MinGW

#1383 MinGW: Refactor Makefile
  sakura_core/Makefile
Labels: MinGW, environment

#1368 MSVCのカスタムターゲットがインクリメンタルビルドに対応できてなかったので対応させたい
  sakura/funccode.targets
  sakura/githash.targets
Labels: environment
