Repository sakura-editor/sakura, pull requests merged in 2020-07, with the labels that each got.

#1332 parse-buildlog.py でエラーの修正のために colors.YELLOW および colors.BLUE を使わない
  parse-buildlog.py
Labels: CI, azure pipelines

#1328 ヘルプの「Windows 10 でのファイル拡張子関連付け」「Grep」「Grep置換」の画像がやたら大きくて見づらい問題に対処
  help/sakura/res/HLP000374.html
  help/sakura/res/images/FileAssoc-1-StartMenu.png
  help/sakura/res/images/FileAssoc-2-Setting.png
  help/sakura/res/images/FileAssoc-3-Application.png
  help/sakura/res/images/FileAssoc-4-DefaultApp.png
  help/sakura/res/images/FileAssoc-5-ChooseDefaultApp.png
  help/sakura/res/images/FileAssoc-6-ChooseDefaultApp.png
  help/sakura/res/images/FileAssoc-7-ChooseDefaultAppTxt.png
  help/sakura/res/images/FileAssoc-8-ChooseDefaultAppTxt.png
  help/sakura/res/images/FileAssoc-9-ChooseTxt-Sakura.png
  help/sakura/res/images/Grep.png
  help/sakura/res/images/GrepReplace.png
Labels: document

#1330 HTMLヘルプの目次に「Windows 10 でのファイル拡張子関連付け」ページが追加されていないので追加
  help/sakura/sakura.hhc
  help/sakura/sakura.hhk
Labels: document

#1321 フォントの拡大縮小操作時にフォントサイズが変わらない場合は処理を行わないように判定追加
  sakura_core/cmd/CViewCommander_Settings.cpp
Labels: :bullettrain_front: speed up :rocket:

#1341 CSelectLangクラスの初期化が必ず行われるようにする
  sakura_core/_main/CProcessFactory.cpp
  sakura_core/dlg/CDlgProfileMgr.cpp
Labels: 🐛bug🦋

#1346 プリプロセッサで定義済みのウィンドウクラス名を使うように変更
  sakura_core/dlg/CDialog.cpp
  sakura_core/func/CFuncKeyWnd.cpp
  sakura_core/print/CPrintPreview.cpp
  sakura_core/util/shell.cpp
  sakura_core/view/CEditView.cpp
  sakura_core/view/CEditView_Mouse.cpp
  sakura_core/view/CEditView_Scroll.cpp
  sakura_core/window/CMainToolBar.cpp
  sakura_core/window/CTabWnd.cpp
Labels: refactoring

#1338 ヘルプのリンクを修正
  help/sakura/res/HLP000059.html
  help/sakura/res/HLP000062.html
Labels: document

#1344 マクロ専用の検索オプションがヘルプに記載されていないので追加する
  help/macro/source/reference/find/S_Replace.html
  help/macro/source/reference/find/S_ReplaceAll.html
  help/macro/source/reference/find/S_SearchNext.html
  help/macro/source/reference/find/S_SearchPrev.html
Labels: document

#1350 英語OSでの初回起動時に設定値を変換する処理を挿入する
  sakura_core/env/CShareData_IO.cpp
Labels: Internationalization
