Repository sakura-editor/sakura, pull requests merged in 2020-01, with the labels that each got.

#1130 ツールバー用のビットマップ管理を分離、結合するツールを導入する (ただし組み込みはしない)
  build-bmp-tools.bat
  ci/azure-pipelines/template.job.build-unittest.yml
  tools/ToolBarTools/.gitattributes
  tools/ToolBarTools/.gitignore
  tools/ToolBarTools/ToolBarImageMuxer/App.config
  tools/ToolBarTools/ToolBarImageMuxer/BmpFileComparer.cs
  tools/ToolBarTools/ToolBarImageMuxer/BmpMuxer.cs
  tools/ToolBarTools/ToolBarImageMuxer/Program.cs
  tools/ToolBarTools/ToolBarImageMuxer/Properties/AssemblyInfo.cs
  tools/ToolBarTools/ToolBarImageMuxer/ToolBarImageMuxer.csproj
  tools/ToolBarTools/ToolBarImageSplitter/App.config
  tools/ToolBarTools/ToolBarImageSplitter/BmpSplitter.cs
  tools/ToolBarTools/ToolBarImageSplitter/Program.cs
  tools/ToolBarTools/ToolBarImageSplitter/Properties/AssemblyInfo.cs
  tools/ToolBarTools/ToolBarImageSplitter/ToolBarImageSplitter.csproj
  tools/ToolBarTools/ToolBarTools.sln
Labels: no-changelog

#1139 CDataProfileの未使用コード(ANSI版)を削除する
  sakura_core/CDataProfile.h
Labels: refactoring

#1142 VS2019 でのコンパイルエラー修正
  sakura_core/mem/CNativeW.cpp
  tests/unittests/test-cnative.cpp
Labels: no-changelog

#1145 CDataProfileの無変換の処理を特殊化する
  sakura_core/CDataProfile.h
Labels: refactoring

#1147 Azure Pipelines で VS2019 のビルドを行う
  azure-pipelines.yml
  ci/azure-pipelines/template.job.build-unittest.yml
  ci/azure-pipelines/template.steps.install-python-modules.yml
Labels: CI, azure pipelines, visual studio 2019

#1149 ドキュメントの誤植を修正
  tools/find-tools.md
Labels: document, no-changelog

#1151 Inno Setup 6 に対応
  tools/find-tools.bat
Labels: CI, appveyor, installer

#1154 Copyright を 2020 にする
  LICENSE
  sakura_core/EditInfo.cpp
  sakura_core/GrepInfo.cpp
  sakura_core/GrepInfo.h
  sakura_core/charset/icu4c/CharsetDetector.cpp
  sakura_core/charset/icu4c/CharsetDetector.h
  sakura_core/extmodule/CIcu4cI18n.cpp
  sakura_core/extmodule/CIcu4cI18n.h
  sakura_core/mem/CPoolResource.h
  sakura_core/recent/CRecentExcludeFile.cpp
  sakura_core/recent/CRecentExcludeFile.h
  sakura_core/recent/CRecentExcludeFolder.cpp
  sakura_core/recent/CRecentExcludeFolder.h
  sakura_core/sakura_rc.rc
  sakura_lang_en_US/sakura_lang_rc.rc
  tests/unittests/coverage.cpp
  tests/unittests/test-StdControl.cpp
  tests/unittests/test-ccommandline.cpp
  tests/unittests/test-cmemory.cpp
  tests/unittests/test-cnative.cpp
  tests/unittests/test-editinfo.cpp
  tests/unittests/test-grepinfo.cpp
  tests/unittests/test-is_mailaddress.cpp
  tests/unittests/test-mydevmode.cpp
  tests/unittests/test-parameterized.cpp
  tests/unittests/test-sample-disabled.cpp
  tests/unittests/test-ssearchoption.cpp
  tools/ChmSourceConverter/ChmSourceConverter.Test/EncoderEscapingFallbackTest.cs
  tools/ChmSourceConverter/ChmSourceConverter.Test/Properties/AssemblyInfo.cs
  tools/ChmSourceConverter/ChmSourceConverter/EncoderEscapingFallback.cs
  tools/ChmSourceConverter/ChmSourceConverter/FileContents.cs
  tools/ChmSourceConverter/ChmSourceConverter/Program.cs
  tools/ChmSourceConverter/ChmSourceConverter/Properties/AssemblyInfo.cs
Labels: document

#1155 CDataProfileの「abortします」コメントを復活する
  sakura_core/CDataProfile.h
Labels: document

#1157 不要ログを削除
  tools/find-tools.bat
Labels: no-changelog

#1156 Universal Ctags の Windows のバイナリ (2020-01-12/feffe43a) に差し替え
  installer/externals/universal-ctags/README.md
  installer/externals/universal-ctags/ctags-2018-09-16_e522743d-x64.zip
  installer/externals/universal-ctags/ctags-2018-09-16_e522743d-x86.zip
  installer/externals/universal-ctags/ctags-2020-01-12_feffe43a-x64.zip
  installer/externals/universal-ctags/ctags-2020-01-12_feffe43a-x86.zip
  sakura/postBuild.bat
Labels: installer

#1158 インストーラに同梱する bregonig.dll を Ver.4.20 にする
  installer/externals/bregonig/README.md
  installer/externals/bregonig/bron412.zip
  installer/externals/bregonig/bron420.zip
  sakura/postBuild.bat
  tools/zip/readme.md
Labels: installer

#1162 Visual Studio のインストールオプションの設定ファイルを追加する
  .vsconfig
Labels: visual studio 2019

#1159 bregonig.dll の zip アーカイブ名を明示する必要のない個所を汎用的な表現に変更する
  installer/externals/bregonig/README.md
  sakura/postBuild.bat
  tools/zip/readme.md
Labels: document, no-changelog

#1163 単体テストのビルドの中間ファイル用のディレクトリを無視リストに追加する
  .gitignore
Labels: Git, no-changelog

#1165 Visual Studio 2017/2019 の環境構築方法に関する説明を更新
  README.md
Labels: document

#1167 find-tools.batの無効にしていたログ出力を復活させる
  tools/find-tools.bat
Labels: no-changelog
