Repository sakura-editor/sakura, pull requests merged in 2021-01, with the labels that each got.

#1490 ステータスバーにフォントサイズの倍率を表示する
  sakura_core/String_define.h
  sakura_core/sakura_rc.rc
  sakura_core/view/CCaret.cpp
  sakura_core/window/CEditWnd.cpp
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: enhancement

#1494 SonarCloudをGitHub Actionsに組み込んで活用したい
  .github/workflows/sonarscan.yml
Labels: CI, GitHub Actions, SonarQube, Test, UnitTest, azure pipelines, static analysis

#1502 mdファイルのみ変更したときにAzure Pipelinesのビルドが走らないようにする
  azure-pipelines.yml
Labels: CI, azure pipelines, document

#1488 CWordParseのテストを追加する
  sakura_core/CSearchAgent.cpp
  sakura_core/parse/CWordParse.cpp
  sakura_core/parse/CWordParse.h
  sakura_core/view/CEditView_Search.cpp
  tests/unittests/test-cwordparse.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: Test

#1509 HTMLヘルプのビルドステップをpowershellに移植してエラー耐性を上げる
  .gitattributes
  appveyor.yml
  build-chm.bat
  help/CompileChm.ps1
  help/extract-chm-from-artifact.ps1
Labels: CI

#1511 SonarCloud解析で検出されたゼロ除算コードに対策する
  sakura_core/cmd/CViewCommander_Window.cpp
Labels: SonarQube, 🐛bug🦋

#1512 exeと設定ファイルのパス取得関数をリファクタリングしてテストできるようにする
  sakura_core/_main/CControlProcess.cpp
  sakura_core/_main/CControlProcess.h
  sakura_core/_main/CProcess.cpp
  sakura_core/_main/CProcess.h
  sakura_core/config/system_constants.h
  sakura_core/dlg/CDlgProfileMgr.cpp
  sakura_core/dlg/CDlgProfileMgr.h
  sakura_core/env/CFileNameManager.cpp
  sakura_core/env/CFileNameManager.h
  sakura_core/env/CSakuraEnvironment.cpp
  sakura_core/env/CShareData.cpp
  sakura_core/env/CShareData.h
  sakura_core/env/CShareData_IO.cpp
  sakura_core/env/DLLSHAREDATA.h
  sakura_core/util/file.cpp
  sakura_core/util/file.h
  tests/unittests/test-cdlgprofilemgr.cpp
  tests/unittests/test-csakuraenvironment.cpp
  tests/unittests/test-file.cpp
  tests/unittests/test-winmain.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: SonarQube, refactoring

#1519 独自関数群tchar_printfを廃止する
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/env/CShareData.cpp
  sakura_core/env/CShareData.h
  sakura_core/util/MessageBoxF.cpp
  sakura_core/util/string_ex.h
  sakura_core/util/tchar_convert.cpp
  sakura_core/util/tchar_convert.h
  sakura_core/util/tchar_printf.cpp
  sakura_core/util/tchar_printf.h
  tests/unittests/test-string_ex.cpp
Labels: refactoring

#1518 help配下のShift_JISファイルのために.gitattributesを追加する
  help/.gitattributes
Labels: Git

#1469 Installer file update (ChineseTranslation)
  appveyor.yml
  installer/Languages/ChineseSimplified(old).isl
  installer/Languages/ChineseSimplified.isl
  installer/Languages/ChineseTraditional(old).isl
  installer/Languages/ChineseTraditional.isl
  installer/Languages/README.md
  installer/instmaterials/info_zh_hans.txt
  installer/instmaterials/info_zh_hant.txt
  installer/sakura-common.iss
Labels: document, enhancement, 🌏Internationalization 🇯🇵 🇺🇸 🇨🇳 🇹🇼

#1524 charset/charcode.(h|cpp): SonarCloud の警告のうち対処が容易なものを解決する
  sakura_core/charset/charcode.cpp
  sakura_core/charset/charcode.h
  sakura_core/parse/CWordParse.cpp
  tests/unittests/test-charcode.cpp
Labels: refactoring
