Repository sakura-editor/sakura, pull requests merged in 2021-09, with the labels that each got.

#1719 Grep 置換ダイアログを表示すると，置換前 と 置換後の両方が選択状態になる現象が発生しないように修正
  sakura_core/dlg/CDlgGrepReplace.cpp
  sakura_core/dlg/CDlgGrepReplace.h
Labels: 🐛bug🦋

#1724 ツールバーの検索ボックスにフォーカスを当てていないにも関わらず文字列が選択状態として表示される現象が起きないように対策
  sakura_core/window/CMainToolBar.cpp
Labels: 🐛bug🦋

#1721 外部コマンド実行でキャンセルした時のメッセージが異なる問題を修正
  sakura_core/view/CEditView_ExecCmd.cpp
Labels: 🐛bug🦋

#1727 プログレスバーの表示切り替え方法を変更して切り替えが正しく反映されるようにする
  sakura_core/uiparts/CVisualProgress.cpp
  sakura_core/window/CMainStatusBar.cpp
  sakura_core/window/CMainStatusBar.h
Labels: 🐛bug🦋

#1728 Grepのビルド警告に対処する
  sakura_core/CGrepAgent.cpp
  sakura_core/view/CEditView_Command.cpp
Labels: refactoring

#1726 uchardet.dll が存在したらそれを使って文字エンコーディングの検出が行われるように処理追加
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/StdAfx.h
  sakura_core/charset/CCodeMediator.cpp
  sakura_core/charset/CharsetDetector.cpp
  sakura_core/charset/CharsetDetector.h
  sakura_core/charset/icu4c/CharsetDetector.cpp
  sakura_core/extmodule/CUchardet.cpp
  sakura_core/extmodule/CUchardet.h
Labels: enhancement
