Repository sakura-editor/sakura, pull requests merged in 2021-10, with the labels that each got.

#1730 sakura.vcxprojのビルド設定を「手作り仕様」に書き替える
  sakura/sakura.vcxproj
Labels: local build

#1731 バージョン情報ダイアログのリファクタリング
  sakura_core/dlg/CDlgAbout.cpp
Labels: refactoring

#1732 CNativeW::AllocStringBufferの失敗時にコピーを中断させる
  sakura_core/view/CEditView.cpp
Labels: 🐛bug🦋
