Repository sakura-editor/sakura, pull requests merged in 2021-04, with the labels that each got.

#1609 フォルダ選択ダイアログを SHBrowseForFolder() でなく IFileDialog を使用するように変更
  sakura_core/dlg/CDlgExec.cpp
  sakura_core/util/shell.cpp
  sakura_core/util/shell.h
Labels: specification change

#1619 タイプ別設定の「カーソル位置縦線」を有効時に、カーソルが先頭行にある状態で PageUp キーを押した後にカーソル左右移動するとカーソル位置縦線が残る問題を修正
  sakura_core/cmd/CViewCommander_Cursor.cpp
Labels: 🐛bug🦋, 💩degradation🧻🚽

#1620 機能種別によるバッファ変換に単体テストを導入する
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/convert/CConvert.cpp
  sakura_core/convert/CConvert.h
  sakura_core/convert/CConvert_CodeAutoToSjis.cpp
  sakura_core/convert/CConvert_CodeAutoToSjis.h
  sakura_core/convert/CConvert_CodeFromSjis.cpp
  sakura_core/convert/CConvert_CodeFromSjis.h
  sakura_core/convert/CConvert_CodeToSjis.cpp
  sakura_core/convert/CConvert_CodeToSjis.h
  sakura_core/view/CEditView.cpp
  tests/unittests/test-cconvert.cpp
  tests/unittests/test-printEFunctionCode.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: UnitTest, refactoring, 🐛bug🦋

#1621 最新のWindows SDKでビルドできるようにする
  vcx-props/vcxcompat.props
Labels: local build, visual studio 2019

#1629 CMemory変更のデグレ対策
  sakura_core/mem/CMemory.cpp
Labels: 🐛bug🦋, 💩degradation🧻🚽

#1634 CConvert_TabToSpace::DoConvert で std::wstring を使用する
  sakura_core/convert/CConvert_TabToSpace.cpp
Labels: refactoring

#1633 Latin1の変換テストを増強する
  tests/unittests/test-ccodebase.cpp
Labels: UnitTest

#1638 CMemory::AppendRawData()でAllocBuffer条件ミスを修正
  sakura_core/mem/CMemory.cpp
Labels: 🐛bug🦋

#1607 Grep結果のタグジャンプの一部リファクタリングと不具合の修正
  sakura_core/cmd/CViewCommander.h
  sakura_core/cmd/CViewCommander_TagJump.cpp
  sakura_core/util/file.cpp
  sakura_core/util/file.h
Labels: refactoring, 🐛bug🦋

#1643 CMemory::AppendRawDataのテストを追加
  tests/unittests/test-cmemory.cpp
Labels: UnitTest

#1642 キャレット位置の文字情報をステータスバーに設定する際の再描画をまとめた変更で UpdateWindow の呼び出しが必要なのに漏れていたのを修正
  sakura_core/view/CCaret.cpp
Labels: 🐛bug🦋

#1644 Cプリプロセッサの判定を強化
  sakura_core/types/CType_Cpp.cpp
Labels: enhancement

#1652 先頭行でPageUp・末尾行でPageDownした後のカーソル移動で下線が残る不具合に対処
  sakura_core/cmd/CViewCommander_Cursor.cpp
  sakura_core/view/CCaret.cpp
Labels: 🐛bug🦋
