Repository sakura-editor/sakura, pull requests merged in 2021-03, with the labels that each got.

#1565 COutputStream::Writeの第2引数をsize_tにする
  sakura_core/io/CStream.h
Labels: refactoring, x64

#1566 ローカル変数fCheckの宣言型を修正する
  sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp
  sakura_core/dlg/CDlgSetCharSet.cpp
Labels: refactoring, x64

#1564 StaticString::Length()の戻り値をintにキャストする
  sakura_core/util/StaticType.h
Labels: refactoring, x64

#1568 DrawTextW 関数の第3引数の型 int に合わせて呼び出すように記述調整
  sakura_core/dlg/CDlgAbout.cpp
  sakura_core/uiparts/CMenuDrawer.cpp
  sakura_core/window/CTipWnd.cpp
Labels: refactoring, x64

#1571 文字幅キャッシュのグローバル関数を削除する
  sakura_core/charset/charcode.cpp
  sakura_core/charset/charcode.h
  sakura_core/doc/layout/CLayoutMgr.cpp
  sakura_core/doc/layout/CLayoutMgr.h
  tests/unittests/test-charcode.cpp
Labels: refactoring

#1570 デザインテンプレートを活用できるように改良する
  sakura_core/util/design_template.h
  tests/unittests/test-design_template.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: IMPORTANT, document, enhancement

#1573 sakura_core/CKeyWordSetMgr.cpp ファイル内のx64ビルド時の警告を除去
  sakura_core/CKeyWordSetMgr.cpp
Labels: refactoring, x64

#1574 sakura_core/view/colors/CColor_Quote.cpp ファイル内のx64ビルド時の警告を除去
  sakura_core/view/colors/CColor_Quote.cpp
Labels: refactoring, x64

#1578 JIS<=>SJIS 変換の際、常に日本語ロケールを使用する
  sakura_core/charset/CEuc.h
  sakura_core/charset/CJis.cpp
  sakura_core/charset/codeutil.cpp
  sakura_core/charset/codeutil.h
Labels: 🐛bug🦋

#1590 WCODE::IsHankaku が文字幅キャッシュを参照しない問題を修正する
  sakura_core/charset/charcode.cpp
  sakura_core/charset/charcode.h
  sakura_core/convert/CConvert.cpp
  sakura_core/convert/CConvert_SpaceToTab.cpp
  sakura_core/convert/CConvert_SpaceToTab.h
  sakura_core/mem/CNativeW.cpp
  sakura_core/mem/CNativeW.h
  tests/unittests/test-cconvert.cpp
  tests/unittests/test-cnative.cpp
Labels: 💩degradation🧻🚽

#1596 バックアップで詳細$0～$9指定を使いMAX_PATH近いパスを保存しようとすると落ちる不具合を修正
  sakura_core/CBackupAgent.cpp
Labels: 🐛bug🦋

#1600 SonarCloudにBugだと言われているCOutlineErlangの問題に対策する
  sakura_core/types/CType_Erlang.cpp
Labels: refactoring

#1602 SonarCloudにBugだと言われているCOutlinePythonの初期化漏れに対処する
  sakura_core/types/CType_Python.cpp
Labels: refactoring

#1604 MinGW版CRTでwcsncat_sのC++オーバーロードが未定義になっていることに対策する
  sakura_core/types/CType_Erlang.cpp
Labels: 🐛bug🦋, 💩degradation🧻🚽

#1599 ファイルダイアログとフォルダ選択ダイアログでのバッファオーバーランを修正
  sakura_core/CFileExt.cpp
  sakura_core/CFileExt.h
  sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp
  sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp
  sakura_core/doc/CDocFileOperation.cpp
  sakura_core/env/CDocTypeManager.cpp
  sakura_core/env/CDocTypeManager.h
  sakura_core/macro/CMacro.cpp
  tests/unittests/test-cdlgopenfile.cpp
  tests/unittests/test-cdoctypemanager.cpp
  tests/unittests/test-cfileext.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: 🐛bug🦋

#1603 Revert "アウトライン解析ダイアログボックスをドッキング時にスプリッターをドラッグしてリサイズするとウィンドウの描画がちらつく問題を解消"
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/sakura_rc.rc
Labels: 🐛bug🦋, 💩degradation🧻🚽

#1601 キャレット位置の文字情報をステータスバーに設定する際の再描画をまとめる
  sakura_core/apiwrap/CommonControl.h
  sakura_core/view/CCaret.cpp
  sakura_core/window/CMainStatusBar.cpp
  sakura_core/window/CMainStatusBar.h
Labels: :bullettrain_front: speed up :rocket:, specification change
