Repository sakura-editor/sakura, pull requests merged in 2021-05, with the labels that each got.

#1630 CI/CDに関係するドキュメントを更新・整理する
  README.md
  SonarQube.md
  appveyor.md
  azure-pipelines.yml
  build.md
  ci/azure-pipelines/azure-pipelines.md
  ci/build-batchfiles.md
  ci/build-envvars.md
Labels: document

#1648 アウトライン解析ウィンドウのツリービューの設定処理の高速化
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/outline/CDlgFuncList.h
Labels: :bullettrain_front: speed up :rocket:

#1654 単体テストに関するドキュメントをサブディレクトリに移動する
  README.md
  azure-pipelines.yml
  tests/unittest.md
  unittest.md
Labels: document

#1656 find-tools.bat のドキュメントを修正する
  tools/find-tools.md
Labels: document

#1658 レイアウト桁位置に対するロジック桁位置の進め方を改善する
  sakura_core/doc/layout/CLayoutMgr.cpp
  sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
  sakura_core/mem/CMemoryIterator.h
  sakura_core/mem/CNativeW.h
  tests/unittests/test-cnative.cpp
Labels: specification change

#1669 GitHub Actions の環境変数をビルドで利用できるようにする
  .github/workflows/build-sakura.yml
  sakura/githash.bat
Labels: CI

#1673 タブ幅が半角単位8桁を超える場合でも下線が最後まで描画されるようにする
  sakura_core/view/figures/CFigure_Comma.cpp
  sakura_core/view/figures/CFigure_Tab.cpp
Labels: 🐛bug🦋

#1685 SonarCloudにBugsだと言われているc++クラス定義の警告に対処する(その2)
  sakura_core/CSearchAgent.cpp
  sakura_core/_main/CControlTray.cpp
  sakura_core/_main/CMutex.h
  sakura_core/_os/CClipboard.h
  sakura_core/_os/CDropTarget.h
  sakura_core/cmd/CViewCommander_Edit_advanced.cpp
  sakura_core/env/DLLSHAREDATA.h
  sakura_core/io/CFile.h
  sakura_core/io/CStream.h
  sakura_core/io/CTextStream.h
  sakura_core/io/CZipFile.h
  sakura_core/macro/CKeyMacroMgr.h
  sakura_core/macro/CMacro.h
  sakura_core/macro/CWSH.h
  sakura_core/mem/CPoolResource.h
  sakura_core/mem/CRecycledBuffer.h
  sakura_core/outline/CDlgFuncList.cpp
  sakura_core/plugin/CPlugin.h
  sakura_core/plugin/CWSHPlugin.h
  sakura_core/print/CPrint.h
  sakura_core/recent/CMRUFile.h
  sakura_core/recent/CMRUFolder.h
  sakura_core/recent/CRecentImp.h
  sakura_core/types/CTypeSupport.h
  sakura_core/uiparts/CGraphics.cpp
  sakura_core/uiparts/CImageListMgr.h
  sakura_core/uiparts/CMenuDrawer.h
  sakura_core/uiparts/CWaitCursor.h
  sakura_core/util/RegKey.h
  sakura_core/util/os.h
  sakura_core/util/relation_tool.h
  sakura_core/util/window.h
  sakura_core/view/CCaret.h
  sakura_core/view/CRuler.h
  sakura_core/view/CViewFont.h
  sakura_core/view/figures/CFigure_Eol.h
Labels: refactoring

#1684 アクティブタブの上部にトップバンドを描画する
  sakura/sakura.vcxproj
  sakura_core/Makefile
  sakura_core/util/window.cpp
  sakura_core/util/window.h
  sakura_core/window/CTabWnd.cpp
  sakura_core/window/CTabWnd.h
  tests/unittests/Makefile
  tests/unittests/tests1.vcxproj
Labels: specification change

#1686 AppveyorのDebugビルドを停止する
  appveyor.yml
Labels: CI, appveyor
