Repository sakura-editor/sakura, pull requests merged in 2021-02, with the labels that each got.

#1528 Wnd_GetText が一文字取りこぼす問題に対処
  sakura_core/apiwrap/StdControl.cpp
  tests/unittests/test-StdControl.cpp
Labels: 💩degradation🧻🚽

#1513 マウスホイールでのフォントサイズ変更をパーセンテージに基づいて行うようにする
  sakura/sakura.vcxproj
  sakura/sakura.vcxproj.filters
  sakura_core/String_define.h
  sakura_core/cmd/CViewCommander_Settings.cpp
  sakura_core/doc/CEditDoc.h
  sakura_core/sakura_rc.rc
  sakura_core/util/zoom.cpp
  sakura_core/util/zoom.h
  sakura_core/view/CCaret.cpp
  sakura_core/window/CEditWnd.cpp
  sakura_core/window/CEditWnd.h
  sakura_lang_en_US/sakura_lang_rc.rc
  tests/unittests/test-winmain.cpp
  tests/unittests/test-zoom.cpp
  tests/unittests/tests1.vcxproj
  tests/unittests/tests1.vcxproj.filters
Labels: specification change

#1537 .vcxproj.filtersのファイル末尾改行を削除する
  .editorconfig
  sakura/sakura.vcxproj.filters
  tests/unittests/tests1.vcxproj.filters
Labels: refactoring

#1536 sakura.iniがない状態で起動した時にマウスホイールでフォントサイズが変更できない問題を修正
  sakura_core/cmd/CViewCommander_Settings.cpp
  tests/unittests/test-winmain.cpp
Labels: 🐛bug🦋

#1543 プロポーショナル版で禁則処理を使えるようにする
  sakura_core/doc/layout/CLayoutMgr.h
  sakura_core/doc/layout/CLayoutMgr_DoLayout.cpp
  sakura_core/doc/layout/CLayoutMgr_New.cpp
Labels: 🐛bug🦋

#1556 CheckSjisChar 関数の第2引数の型を int から size_t に変更
  sakura_core/charset/codechecker.cpp
  sakura_core/charset/codechecker.h
Labels: refactoring

#1558 CESI::_CheckUtf16Eol の第2引数の型を int から size_t に変更
  sakura_core/charset/CESI.cpp
  sakura_core/charset/CESI.h
Labels: refactoring

#1557 CheckEucjpChar 関数の第2引数の型を int から size_t に変更
  sakura_core/charset/codechecker.cpp
  sakura_core/charset/codechecker.h
Labels: refactoring
