Repository sakura-editor/sakura, pull requests merged in 2022-12, with the labels that each got.

#1873 リリース用に githash.bat を修正、HTMLヘルプ中のバージョン番号を変更
  help/sakura/res/HLP000001.html
  sakura/githash.bat
Labels: Release

#1878 メニューのスペル間違いを修正
  sakura_lang_en_US/sakura_lang_rc.rc
Labels: 🌏Internationalization 🇯🇵 🇺🇸 🇨🇳 🇹🇼

#1877 v2.4.2 の CHANGELOG.md を適用
  CHANGELOG.md
Labels: document, Release

#1882 色種別リスト オーナー描画のDPIスケーリング対応を改良
  sakura_core/typeprop/CPropTypes.h
  sakura_core/typeprop/CPropTypesColor.cpp
Labels: 🐛bug🦋
