Repository sakura-editor/sakura, pull requests merged in 2025-06, with the labels that each got.

#2076 綴り間違い修正 (Clipborad / Clipboard)
  sakura_core/_os/CClipboard.cpp
  sakura_core/_os/CClipboard.h
  sakura_core/macro/CMacro.cpp
  tests/unittests/test-cclipboard.cpp
Labels: no-changelog

#2077 define STRICT 削除
  sakura_core/_main/global.h
  tests/unittests/test-cdlgopenfile.cpp
Labels: refactoring

#2078 "typedef std::wstring wstring" 削除
  sakura_core/CGrepEnumKeys.h
  sakura_core/CProfile.cpp
  sakura_core/CProfile.h
  sakura_core/dlg/CDlgPluginOption.cpp
  sakura_core/dlg/CDlgPluginOption.h
  sakura_core/env/CSakuraEnvironment.cpp
  sakura_core/macro/CCookieManager.cpp
  sakura_core/macro/CCookieManager.h
  sakura_core/plugin/CDllPlugin.cpp
  sakura_core/plugin/CDllPlugin.h
  sakura_core/plugin/CJackManager.cpp
  sakura_core/plugin/CJackManager.h
  sakura_core/plugin/COutlineIfObj.h
  sakura_core/plugin/CPlugin.cpp
  sakura_core/plugin/CPlugin.h
  sakura_core/plugin/CPluginIfObj.h
  sakura_core/plugin/CPluginManager.cpp
  sakura_core/plugin/CPluginManager.h
  sakura_core/plugin/CSmartIndentIfObj.h
  sakura_core/plugin/CWSHPlugin.h
  sakura_core/prop/CPropComMainMenu.cpp
  sakura_core/prop/CPropComPlugin.cpp
  sakura_core/typeprop/CDlgTypeAscertain.h
  sakura_core/typeprop/CDlgTypeList.cpp
  sakura_core/typeprop/CDlgTypeList.h
  sakura_core/typeprop/CImpExpManager.cpp
  sakura_core/typeprop/CImpExpManager.h
Labels: refactoring

#2087 Azure Pipeline でのみ実装されている MinGW でのコンパイル処理を GitHub Actions に移植する
  .github/workflows/build-on-msys2.yml
Labels: CI, azure pipelines, GitHub Actions

#2086 Azure Pipeline でのみ実装されている文字コードチェックの 処理を GitHub Actions に移植する
  .github/workflows/check-encoding.yml
Labels: CI, azure pipelines, GitHub Actions

#2089 GitHub Actions へ集約のために azure pipeline の JOB を削除
  azure-pipelines.yml
  ci/azure-pipelines/azure-SonarQube-schedule1.png
  ci/azure-pipelines/azure-SonarQube-schedule2.png
  ci/azure-pipelines/azure-SonarQube-schedule3.png
  ci/azure-pipelines/azure-SonarQube.png
  ci/azure-pipelines/azure-pipelines.md
  ci/azure-pipelines/template.job.SonarQube.yml
  ci/azure-pipelines/template.job.build-on-msys2.yml
  ci/azure-pipelines/template.job.build-unittest.yml
  ci/azure-pipelines/template.job.checkEncoding.yml
  ci/azure-pipelines/template.job.cppcheck.yml
  ci/azure-pipelines/template.job.doxygen.yml
  ci/azure-pipelines/template.job.python-check.yml
  ci/azure-pipelines/template.steps.install-mingw-w64-gcc.yml
  ci/azure-pipelines/template.steps.install-python-modules.yml
Labels: CI, azure pipelines

#2091 GitHub Actions へ集約のために appveyor を削除
  appveyor.yml
  ci/appveyor/appveyor-SonarQube.png
Labels: CI, appveyor

#2092 parse-buildlog.bat および関連ファイルを削除
  appveyor_env.py
  build-sln.bat
  ci/build-batchfiles.md
  parse-buildlog.bat
  parse-buildlog.py
Labels: CI, GitHub Actions

#2095 CF_UNICODETEXT形式のクリップボードデータをサクラエディタにペーストしたときに u+0000 が追加される不具合を修正
  sakura_core/_os/CClipboard.cpp
  sakura_core/_os/CClipboard.h
  sakura_core/cmd/CViewCommander_Clipboard.cpp
Labels: 🐛bug🦋

#2093 Azure Pipeline 用の変数定義および説明を削除
  ci/build-envvars.md
  sakura/githash.bat
Labels: CI, azure pipelines

#2079 test code 削除 (CommonSetting.cpp)
  sakura_core/env/CommonSetting.cpp
Labels: refactoring

#2080 ComCtl32.dll バージョン 6 を使用したコントロールのサブクラス化 (CDlgSameColor)
  sakura_core/typeprop/CDlgSameColor.cpp
  sakura_core/typeprop/CDlgSameColor.h
  sakura_core/typeprop/CPropTypesWindow.cpp
Labels: refactoring

#2097 appveyor 用の変数定義および説明を削除
  .gitignore
  build-sln.bat
  ci/build-envvars.md
  help/make-artifacts.bat
  sakura/githash.bat
  tests/run-tests.bat
  tests/test_result_filter_tell_AppVeyor.bat
  tests/unittest.md
  zipArtifacts.bat
Labels: CI, appveyor

#2098 README.md から Azure Pipeline を削除
  README.md
Labels: document, CI, azure pipelines

#2099 azure pipeline と appveyor の説明を削除
  README.md
  SonarQube.md
  build.md
  ci/build-batchfiles.md
Labels: document, CI, azure pipelines, appveyor
